/* Fiv-o content: sales plays (the "leaves" discovery narrows to).
   Built from public Nutanix GTM material (Sept 2026). Proof points carry a source URL;
   anything marked verify:true should be checked against current internal enablement
   before you quote it to a customer. Overlay your own battlecards freely. */
(function (F) {
  'use strict';

  const S = {
    transition: 'https://www.nutanix.com/vmware-alternative/transition',
    analyst: 'https://www.nutanix.com/blog/one-platform-four-analyst-recognitions-across-modern-infrastructure-and-ai',
    next26: 'https://www.nutanix.com/blog/top-next-2026-news',
    expedient: 'https://expedient.com/knowledgebase/blog/2026-04-16-key-takeaways-from-nutanix-next-2026/',
    tenk: 'https://www.sec.gov/Archives/edgar/data/0001618732/000119312526394793/ntnx-20260731.htm',
    options: 'https://www.nutanix.com/products/cloud-platform/software-options',
    everpure: 'https://blog.purestorage.com/solutions/nutanix-support-on-flasharray-available-pure-storage/',
    nc2: 'https://www.nutanix.com/products/nutanix-cloud-clusters',
    platform26: 'https://www.nutanix.com/press-releases/2026/nutanix-delivers-complete-platform-for-the-agentic-ai-era',
    ncm: 'https://www.nutanix.com/library/datasheets/ncm',
    security: 'https://www.nutanix.com/products/security',
    flow: 'https://www.nutanix.com/products/flow-network-security',
    datalens: 'https://ir.nutanix.com/news-releases/news-release-details/nutanix-strengthens-cyber-resilience-accelerated-ransomware',
    veeamObj: 'https://www.veeam.com/sys976',
    nciEdge: 'https://www.nutanix.com/library/datasheets/nci-edge',
    omnissa: 'https://www.nutanix.com/omnissa',
    citrix: 'https://www.nutanix.com/solutions/vdi/citrix',
    ndb: 'https://www.nutanix.com/products/database-service',
    ndb210: 'https://www.nutanix.com/blog/introducing-nutanix-database-service-v2-10',
    ndbFit: 'https://www.nutanix.com/blog/accelerate-your-database-modernization-with-the-nutanix-database-service-ndb-fitment-tool',
    nkp: 'https://www.nutanix.com/products/kubernetes-management-platform',
    nai: 'https://www.nutanix.com/products/nutanix-enterprise-ai',
    agentGw: 'https://www.nutanix.com/blog/introducing-nutanix-agent-gateway',
    agentic: 'https://www.nutanix.com/press-releases/2026/nutanix-unveils-nutanix-agentic-ai',
  };
  F.sources = S;

  F.plays = [
    {
      id: 'vmw',
      name: 'VMware Exit → Modernize on Nutanix',
      short: 'VMware exit',
      products: ['NCI (AOS + AHV)', 'Prism Central', 'Nutanix Move', 'Flow Network Security', 'NCM (optional)'],
      oneLiner: 'Decide your virtualization future on your terms, not Broadcom’s timeline: AHV on a platform that runs on the hardware, storage and cloud you choose, with a de-risked migration path.',
      before: 'Forced VCF/VVF bundles, a renewal quote that blew up the budget, and the vSphere 8 end-of-general-support date (Oct 2027) setting the timeline instead of the business.',
      after: 'Predictable subscription on portable licenses, one console (Prism) for VMs, storage, networking and DR, and a migration you control with Move and zero-copy conversion.',
      capabilities: [
        'Migrate VMs with minimal downtime (Move incremental sync + scheduled cutover)',
        'HA, live migration, dynamic scheduling (ADS), snapshots and replication built in',
        'Microsegmentation that covers the NSX DFW use case (Flow Network Security)',
        'Hardware choice: HCI nodes or existing external storage',
        'Backup and business-app vendor support on AHV',
      ],
      personas: {
        exec: 'This is a chance to set your platform strategy on your terms. Nutanix gives you a portable, modular subscription — buy what you use — and a proven migration path. Many teams use the renewal delta to fund the move; let’s model yours.',
        infra: 'AHV comes with NCI: HA, live migration, ADS scheduling, snapshots and replication, all in Prism next to storage and networking. Move handles the migration and LCM does one-click upgrades from firmware to hypervisor.',
        netsec: 'Flow Network Security gives you category-based microsegmentation policies — the NSX DFW use case — from Prism Central, and the Palo Alto Networks integrations extend Zero Trust across the estate.',
        storage: 'If the array is recent, keep it: NCI Compute runs on Everpure FlashArray and Dell PowerFlex today, with NetApp ONTAP, Dell PowerStore and Lenovo ThinkSystem announced. If not, AOS turns local drives into resilient distributed storage.',
        finance: 'Term subscriptions, core-based licensing that is portable across hardware and public cloud (NC2), and no mandated bundle. We’ll build a side-by-side TCO against the renewal quote.',
        euc: 'Omnissa Horizon 8 and Citrix both support AHV — your desktops come with you.',
        platform: 'If Tanzu/VKS was on the roadmap, NKP runs on AHV (and elsewhere) with fleet management and GitOps.',
      },
      proof: [
        { t: 'Named a Leader in the 2026 Gartner Magic Quadrant for Server Virtualization Platforms (Nutanix-reported).', src: S.transition, verify: true },
        { t: 'Leader in the 2026 Gartner Magic Quadrant for Distributed Hybrid Infrastructure.', src: S.analyst },
        { t: 'UK credit union reported 39% savings in total cost of operations after moving.', src: S.transition },
        { t: 'Zero-copy migration from vSphere (e.g., vVols on Everpure) converts VMs in place without duplicating data — announced at .NEXT 2026; confirm supported storage configs.', src: S.expedient, verify: true },
        { t: 'Customer Net Promoter Score of 90+ (Nutanix-reported).', src: S.transition },
      ],
      objections: [
        { q: 'Migration is too risky / too much downtime.', a: 'Move replicates incrementally and cuts over on your schedule; zero-copy conversion applies for supported storage. Start with a low-risk wave, prove it in a POC, and keep a rollback path.' },
        { q: 'Our team only knows VMware.', a: 'Prism is a single console for compute, storage, networking and DR, so most admins are productive quickly. Offer a Test Drive and Nutanix University training.' },
        { q: 'Will our apps and backup be supported?', a: 'Check the AHV-validated application list. Veeam, Commvault, Rubrik, Cohesity and HYCU all protect AHV.' },
        { q: 'We’ll just negotiate VMware down.', a: 'Ask what happens at the next renewal and when vSphere 8 general support ends (Oct 2027). A credible alternative is leverage either way, but price-only deals stall — find the ops, hardware or DR pain.' },
        { q: 'We just bought new storage.', a: 'Keep it: NCI Compute on external storage (Everpure FlashArray and Dell PowerFlex supported; NetApp ONTAP, Dell PowerStore and Lenovo ThinkSystem announced — verify GA).' },
      ],
      nextSteps: [
        'Run Nutanix Collector (or export RVTools) → size in Nutanix Sizer',
        'TCO comparison against the renewal quote',
        'Tailored AHV/Prism demo or Nutanix Test Drive',
        'Move migration assessment for a pilot wave',
        'POC on one application tier',
      ],
      editions: 'NCP bundles: Starter (NCI Pro + NCM Pro), Pro (NCI Ultimate + NCM Pro), Ultimate (NCI Ultimate + NCM Ultimate). Confirm which tier carries Flow and sync/Metro DR for this deal.',
      editionsSrc: S.options,
      qualifiers: ['vmw.renewal', 'vmw.intent', 'env.storage'],
      variants: [
        { id: 'hci', name: 'Full-stack HCI', products: ['NCI on NX / Dell / HPE / Lenovo / Cisco / Fujitsu'], pitch: 'Collapse servers and SAN into a scale-out cluster you grow a node at a time; storage, hypervisor and firmware upgraded together with 1-click LCM.' },
        { id: 'ext', name: 'Keep-your-array (NCI Compute + external storage)', products: ['NCI Compute', 'Everpure FlashArray / Dell PowerFlex (GA)', 'NetApp ONTAP / Dell PowerStore / Lenovo ThinkSystem (announced 2026 — verify)'], pitch: 'Change the hypervisor, keep the storage investment: AHV and Prism on the array you already own, with VM-level operations in Prism.' },
        { id: 'nc2', name: 'Cloud landing on NC2', products: ['NC2 on AWS / Azure / GCP / OVHcloud', 'Nutanix Move'], pitch: 'Exit VMC/AVS/GCVE or a datacenter without refactoring: run the same Nutanix stack on bare-metal cloud instances and move VMs as-is.' },
      ],
    },

    {
      id: 'refresh',
      name: 'Infrastructure Refresh → HCI Simplicity',
      short: 'HCI refresh',
      products: ['NCI (AOS + AHV)', 'Prism', 'Life Cycle Manager (LCM)', 'OEM hardware (Dell, HPE, Lenovo, Cisco, Fujitsu) or NX'],
      oneLiner: 'Replace the three-tier refresh (servers + SAN + fabric) with a scale-out platform you grow a node at a time and upgrade with one click.',
      before: 'A big-bang refresh every five years, overbuying capacity up front, several vendors to patch and blame, and hardware lead times you can’t control.',
      after: 'Buy for today and scale in small steps, one support call, firmware-to-hypervisor upgrades orchestrated by LCM, and hardware choice across the major OEMs.',
      capabilities: [
        'Scale out one node at a time; mix hardware generations',
        '1-click, non-disruptive LCM upgrades (firmware → hypervisor)',
        'Storage efficiency (compression, dedupe, erasure coding) with no LUN management',
        'Choice of OEM hardware or NX',
      ],
      personas: {
        exec: 'Stop doing forklift refreshes. You buy what you need now, grow in small steps, and get one platform and one support number instead of three vendors pointing at each other.',
        infra: 'LCM upgrades firmware, AOS and AHV as a rolling, non-disruptive operation — no more weekend windows for a refresh cycle.',
        storage: 'No LUNs, zoning or RAID groups: AOS pools local flash across nodes with built-in data services and self-healing.',
        finance: 'Pay-as-you-grow instead of five-year overbuy; software licenses are portable when the hardware changes.',
      },
      proof: [
        { t: 'Leader in the 2026 Gartner Magic Quadrant for Distributed Hybrid Infrastructure.', src: S.analyst },
        { t: 'Runs on qualified hardware from Cisco, Dell, Fujitsu, HPE and Lenovo (co-branded offerings) and on HPE GreenLake.', src: S.tenk },
      ],
      objections: [
        { q: 'HCI can’t scale storage independently.', a: 'Storage-heavy nodes, compute-only nodes and external storage options cover unbalanced growth.' },
        { q: 'We’re happy with our SAN.', a: 'Then keep it — NCI Compute with external storage is a supported architecture. HCI is a choice, not a requirement.' },
        { q: 'Hyper-V / Azure Local is “free” with our Microsoft agreement.', a: 'Plant questions on tool sprawl, cloud-connectivity requirements, hardware lists and who owns upgrades across the stack.' },
      ],
      nextSteps: ['Collector / RVTools → Sizer', 'Reference-architecture whiteboard', 'Nutanix Test Drive', 'OEM quote alignment with the partner'],
      editions: 'Most refreshes land on NCP Starter or Pro; check whether DR/security needs push to NCI Ultimate.',
      editionsSrc: S.options,
      qualifiers: ['hw.what', 'hw.when'],
    },

    {
      id: 'ops',
      name: 'Simplify & Automate Operations',
      short: 'Simplify ops',
      products: ['Prism Central', 'LCM', 'NCM Intelligent Operations', 'NCM Self-Service', 'NCM Cost Governance'],
      oneLiner: 'Give a small IT team its evenings back: one console, one-click upgrades, capacity forecasting, and self-service instead of tickets.',
      before: 'Too many consoles, weekend patch windows, surprise capacity crunches, and a ticket for every VM.',
      after: 'Prism as one pane; LCM one-click upgrades; NCM capacity runway and anomaly detection; low-code automation; a self-service catalog with guardrails; cost visibility on-prem and in cloud (NCM 2.0).',
      capabilities: [
        'Non-disruptive 1-click upgrades',
        'Capacity runway forecasting and what-if planning',
        'Low-code automation playbooks (X-Play)',
        'Self-service catalog with quotas and approvals',
        'Showback / cost governance across on-prem and cloud',
      ],
      personas: {
        exec: 'Your team is spending its time keeping the lights on. We give those hours back to projects the business actually asked for — and we can quantify it.',
        infra: 'One console for compute, storage, network and DR; LCM handles rolling upgrades; NCM tells you capacity runway in days and automates the routine fixes.',
        finance: 'NCM Cost Governance gives showback across on-prem and public cloud in one console, so you can see what each team consumes.',
        platform: 'Self-Service blueprints give app teams a governed catalog instead of a ticket queue.',
      },
      proof: [
        { t: 'NCM 2.0 brings Cost Governance on-premises alongside AIOps and Self-Service in one console.', src: S.platform26 },
        { t: 'NCM covers intelligent operations, self-service/orchestration, security visibility and cost governance.', src: S.ncm },
        { t: 'Customer NPS of 90+ (Nutanix-reported).', src: S.transition },
      ],
      objections: [
        { q: 'We already have monitoring tools.', a: 'Keep them for apps. Prism/NCM add platform-aware capacity planning, right-sizing and automated remediation that generic monitors don’t.' },
        { q: 'We don’t have time to learn automation.', a: 'X-Play is low-code “if this, then that” — start with two playbooks (e.g., auto-add memory, ticket on anomaly).' },
      ],
      nextSteps: ['“Day in the life” ops demo: upgrade, capacity runway, X-Play', 'Quantify hours/quarter spent on patching and upgrades for the TCO', 'Nutanix Test Drive'],
      editions: 'NCM Pro vs Ultimate determines automation/self-service depth — map requirements before quoting.',
      editionsSrc: S.options,
      qualifiers: ['env.itteam', 'ops.upgrades'],
    },

    {
      id: 'dr',
      name: 'Business Continuity & Disaster Recovery',
      short: 'BC/DR',
      products: ['Nutanix Disaster Recovery (async / NearSync / sync)', 'Metro Availability', 'Recovery plans', 'NC2 as DR target', 'Partner DRaaS'],
      oneLiner: 'Make DR something you test on a Tuesday, not something you hope works: built-in replication and orchestrated recovery plans to a second site or the cloud.',
      before: 'Backups but no tested recovery, SRM/Zerto licensing and complexity, or no second site at all.',
      after: 'Policy-based protection per app category, recovery plans with non-disruptive test failovers, RPOs from hours to near-zero, and cloud DR on NC2 without building a second datacenter.',
      capabilities: [
        'Policy-based replication (async, NearSync, sync) by app category',
        'Orchestrated recovery plans with non-disruptive test failover',
        'Cloud DR target on NC2 (AWS / Azure / GCP)',
        'Simple failback',
      ],
      personas: {
        exec: 'Right now recovery is a hope, not a plan. We make it a tested, documented, one-click process — and we can do it without buying a second datacenter.',
        infra: 'Protection policies follow VM categories; recovery plans handle boot order, IP mapping and scripts, and you can test-failover into an isolated network any time.',
        finance: 'Cloud DR on NC2 lets you keep the DR footprint small until you need it instead of paying for a mirrored site.',
        netsec: 'Auditors and cyber-insurers want proof of recovery — test-failover reports give you that evidence.',
      },
      proof: [
        { t: 'NC2 use cases include cloud DR, on-demand burst, datacenter exit and regional expansion; clusters deploy in as little as ~30 minutes.', src: S.nc2, verify: true },
        { t: 'Nutanix Disaster Recovery covers on-prem, public cloud and managed-service-provider options.', src: S.tenk },
      ],
      objections: [
        { q: 'Our backup vendor does DR.', a: 'Backup restores data; DR restores running services in order. Ask how long a full restore of tier-1 would take and when it was last tested.' },
        { q: 'We can’t afford a second site.', a: 'That’s the NC2/DRaaS pattern — keep the cloud footprint small until failover.' },
      ],
      nextSteps: ['DR design session: app tiers → RPO/RTO → policy', 'NC2 DR sizing', 'Live demo of test failover'],
      editions: 'Sync replication and Metro typically need higher NCI tiers — confirm against the software options page.',
      editionsSrc: S.options,
      qualifiers: ['res.dr', 'res.rpo'],
      variants: [
        { id: 'site', name: 'Nutanix DR to a second site', products: ['Nutanix DR', 'Metro Availability'], pitch: 'Replicate to your second site or colo with policy-based protection; Metro for near-zero RPO where latency allows.' },
        { id: 'cloud', name: 'DR to the cloud (NC2 / DRaaS)', products: ['NC2 on AWS / Azure / GCP', 'Partner DRaaS'], pitch: 'No second datacenter needed: recover natively into NC2 in the public cloud or through a Nutanix service provider.' },
      ],
    },

    {
      id: 'cyber',
      name: 'Cyber Resilience & Ransomware Recovery',
      short: 'Cyber resilience',
      products: ['Flow Network Security (microsegmentation)', 'Data Lens', 'Immutable snapshots / Objects WORM', 'Data-at-rest encryption', 'Automated security hardening', 'Palo Alto Networks integration'],
      oneLiner: 'Contain the blast radius, catch ransomware on file data early, and recover clean copies fast — built into the platform, not bolted on.',
      before: 'A flat network where ransomware moves freely, backups that aren’t immutable, an unknown recovery time, and a cyber-insurance questionnaire full of gaps.',
      after: 'App-level microsegmentation, anomaly detection and guided recovery for file data, immutable snapshots and backup targets, one-click encryption and self-healing hardening.',
      capabilities: [
        'Microsegmentation by app/category to stop lateral movement',
        'Ransomware detection on unstructured data with guided recovery',
        'Immutable (WORM) snapshots and backup targets',
        'One-click data-at-rest encryption',
        'Security baseline enforcement and audit reporting',
      ],
      personas: {
        exec: 'The question isn’t whether you get hit, it’s how far it spreads and how fast you’re back. We shrink the blast radius and give you a recovery time you can put in front of the board and the insurer.',
        netsec: 'Flow applies microsegmentation policies by category from Prism Central — no hairpinning through the perimeter firewall — and integrates with Palo Alto Networks for Zero Trust.',
        infra: 'Encryption, hardening and snapshots are platform settings, not extra projects. Data Lens watches file shares for ransomware patterns and walks you through recovery.',
        storage: 'Objects with WORM is a Veeam Ready immutable repository; Files snapshots plus Data Lens give you clean restore points.',
      },
      proof: [
        { t: 'Data Lens: detect a threat, defend, and begin 1-click recovery within 20 minutes of exposure (unstructured data).', src: S.datalens },
        { t: 'Nutanix Objects qualified as Veeam Ready Object with Immutability.', src: S.veeamObj },
        { t: 'Palo Alto Networks named Nutanix 2026 Global Security Partner of the Year; integrations extend Zero Trust across infrastructure and cloud.', src: S.next26 },
      ],
      objections: [
        { q: 'Our firewall and EDR already cover this.', a: 'Perimeter and endpoint don’t stop east-west spread between VMs. Ask what stops a compromised VM reaching the backup server.' },
        { q: 'Microsegmentation is too hard to operate.', a: 'Flow policies are category-based and visual; start in monitor mode on one app, then enforce.' },
      ],
      nextSteps: ['Security posture workshop (segmentation map for 1–2 critical apps)', 'Data Lens trial on file shares', 'Recovery-time exercise: “ransomware on Monday” tabletop'],
      editions: 'Flow Network Security and Data Lens are licensed separately or in higher tiers — confirm.',
      editionsSrc: S.options,
      qualifiers: ['res.event', 'res.network'],
    },

    {
      id: 'nc2',
      name: 'Hybrid Multicloud with NC2',
      short: 'NC2 hybrid cloud',
      products: ['NC2 on AWS / Azure / GCP / OVHcloud', 'Nutanix Move', 'Portable licensing', 'NCM Cost Governance', 'Nutanix Central'],
      oneLiner: 'Use the public cloud on your terms: run the same Nutanix stack on bare-metal cloud instances — no refactoring, same tools, same licenses.',
      before: 'A datacenter lease running out, a cloud migration stalled by refactoring cost, or cloud bills far above plan.',
      after: 'Lift-and-shift in weeks, burst and DR capacity on demand, one operating model everywhere, and licenses that move both ways (including back on-prem).',
      capabilities: [
        'Run VMs unchanged on bare-metal cloud instances',
        'Same Prism operations and security policies on-prem and in cloud',
        'Portable licenses across on-prem and cloud',
        'Cost visibility across environments',
      ],
      personas: {
        exec: 'You get the cloud’s speed without a refactoring program, and you keep the option to move workloads back when the economics change.',
        infra: 'It’s the same AOS/AHV stack on bare metal in AWS, Azure, GCP or OVHcloud — same Prism, same runbooks, same backup tools.',
        finance: 'Portable licenses and cloud commits (e.g., marketplace purchases) can work together; NCM Cost Governance shows spend across both.',
      },
      proof: [
        { t: 'NC2 runs on AWS, Azure, Google Cloud and OVHcloud.', src: S.tenk },
        { t: 'Core NC2 use cases: cloud DR, on-demand burst, datacenter exit and regional expansion; clusters online in as little as ~30 minutes.', src: S.nc2, verify: true },
        { t: '.NEXT 2026 highlighted sovereign-cloud options (e.g., AWS European Sovereign Cloud).', src: S.next26, verify: true },
      ],
      objections: [
        { q: 'Bare metal in cloud is expensive.', a: 'Compare against refactor cost and time plus the run cost of native VMs; NC2 is often the bridge, not the destination.' },
        { q: 'We’re going cloud-native anyway.', a: 'NC2 moves the long tail of VMs now; NKP supports the apps you do refactor.' },
      ],
      nextSteps: ['NC2 sizing with the cloud account team', 'Cloud landing-zone design session', 'NC2 test drive / pilot'],
      editions: 'NC2 uses the same NCI/NCM licensing — confirm portability terms and cloud marketplace options.',
      editionsSrc: S.options,
      qualifiers: ['cloud.direction', 'cloud.refactor'],
    },

    {
      id: 'nus',
      name: 'Unified Storage (Files · Objects · Volumes)',
      short: 'Unified storage',
      products: ['Nutanix Unified Storage — Files, Objects, Volumes', 'Data Lens', 'Smart Tiering'],
      oneLiner: 'Consolidate file servers, NAS and backup targets onto one software-defined storage platform with built-in ransomware protection.',
      before: 'Windows file servers everywhere, an aging NAS filer, backup repositories with no immutability, and a separate silo for every data type.',
      after: 'One platform for file, object and block, scaled out on the same infrastructure, with WORM, tiering to cloud and Data Lens analytics.',
      capabilities: [
        'Scale-out SMB/NFS file services',
        'S3-compatible object storage with WORM / object lock',
        'Tiering to public cloud S3',
        'Ransomware detection and audit on file data',
      ],
      personas: {
        exec: 'Fewer storage silos, one support contract, and backups that ransomware can’t encrypt.',
        storage: 'Files replaces file servers and filers with scale-out shares; Objects gives you an S3 immutable repository for Veeam/Commvault; everything is managed in Prism.',
        netsec: 'Data Lens audits who touched what and flags ransomware-like behavior on shares.',
        ai: 'Objects can act as a high-performance data tier for AI pipelines.',
      },
      proof: [
        { t: 'NUS 5.3 expands Smart Tiering to Google Cloud and OVHcloud S3 and positions Objects as a performance tier for AI.', src: S.platform26 },
        { t: 'Nutanix Objects qualified as Veeam Ready Object with Immutability.', src: S.veeamObj },
      ],
      objections: [
        { q: 'Our NAS vendor has more features.', a: 'List the features actually in use; most file workloads need SMB/NFS, snapshots, replication, quotas and auditing — all in Files.' },
      ],
      nextSteps: ['Unstructured data assessment (capacity, growth, protocols)', 'Objects as a Veeam/Commvault target pilot', 'Data Lens trial'],
      editions: 'NUS is licensed per TiB — size capacity and growth.',
      editionsSrc: S.options,
      qualifiers: ['stor.types'],
      variants: [
        { id: 'files', name: 'File consolidation (Nutanix Files)', products: ['Nutanix Files', 'Data Lens'], pitch: 'Retire Windows file servers and NAS filers onto scale-out Files with ransomware detection built in.' },
        { id: 'objects', name: 'S3 & immutable backup target (Nutanix Objects)', products: ['Nutanix Objects', 'WORM / object lock'], pitch: 'An on-prem S3 repository with immutability for backups, archives and AI data, tiered to cloud as needed.' },
      ],
    },

    {
      id: 'edge',
      name: 'Remote Office & Edge',
      short: 'ROBO / edge',
      products: ['NCI-Edge', 'NCM-Edge', 'Small 1–3 node clusters', 'Prism Central / Nutanix Central fleet management', 'NKP for edge containers'],
      oneLiner: 'Run every branch like part of one datacenter: small-footprint clusters, centrally managed upgrades and monitoring — no IT staff on site.',
      before: 'A few servers and a small NAS per site, someone driving out for upgrades, inconsistent backups and no visibility.',
      after: 'Right-sized clusters per site, fleet-wide upgrades and policies from one console, and local resilience when the WAN drops.',
      capabilities: ['Small-footprint clusters per site', 'Central fleet upgrades and monitoring', 'Replication back to the core site', 'Edge licensing (NCI-Edge / NCM-Edge)'],
      personas: {
        exec: 'Every site gets the same resilience as HQ without putting IT people on the road.',
        infra: 'Prism Central manages the fleet: one-click upgrades across sites, central alerting, and replication home.',
        finance: 'Edge-specific licensing keeps small sites affordable.',
      },
      proof: [{ t: 'NCI-Edge and NCM-Edge editions are purpose-built for distributed and remote sites.', src: S.nciEdge }],
      objections: [{ q: 'Sites are too small for HCI.', a: 'Small 1–3 node options exist; confirm the minimum configuration for each site’s resilience needs.' }],
      nextSteps: ['Site inventory (apps, VMs, bandwidth per site)', 'Fleet-management demo'],
      editions: 'NCI-Edge / NCM-Edge — confirm per-site VM limits.',
      editionsSrc: S.nciEdge,
      qualifiers: ['edge.staff'],
    },

    {
      id: 'euc',
      name: 'End-User Computing on AHV',
      short: 'VDI / EUC',
      products: ['Citrix on Nutanix', 'Omnissa Horizon 8 on AHV', 'Nutanix Files (profiles)', 'NC2 for desktop burst'],
      oneLiner: 'Keep your VDI broker, lose the VMware dependency: Horizon and Citrix run on AHV with linear scale and fast provisioning.',
      before: 'Horizon tied to a VMware bundle, boot and login storms, painful image updates, and a high cost per desktop.',
      after: 'Predictable per-node scaling, fast clone provisioning, profiles on Files, and the option to burst desktops into NC2.',
      capabilities: ['Supported broker on AHV (Citrix / Horizon)', 'Fast, space-efficient clones', 'Linear scale per node', 'Profile/home storage on Files'],
      personas: {
        euc: 'Horizon 8 now supports AHV with Prism Central-driven provisioning and redirect-on-write clones; Citrix has long been supported. Desktops scale predictably node by node.',
        exec: 'Your desktop platform stops being hostage to a hypervisor bundle.',
        finance: 'Cost per desktop drops when VDI no longer pulls the full VMware bundle along with it.',
      },
      proof: [
        { t: 'Omnissa Horizon 8 supports Nutanix AHV (partnership announced May 2025), with Prism Central provisioning and redirect-on-write cloning.', src: S.omnissa },
        { t: 'Citrix DaaS / CVAD on Nutanix for hybrid multicloud EUC.', src: S.citrix },
      ],
      objections: [{ q: 'Our Horizon/Citrix team won’t want to change.', a: 'They don’t change their broker — only the hypervisor and platform underneath.' }],
      nextSteps: ['VDI sizing (users, persona types, GPU)', 'Login VSI-style pilot'],
      editions: 'Check EUC-specific licensing options (per-user vs per-core).',
      editionsSrc: S.options,
      qualifiers: ['euc.platform'],
      variants: [
        { id: 'citrix', name: 'Citrix on Nutanix', products: ['Citrix CVAD / DaaS', 'AHV'], pitch: 'Mature Citrix-on-AHV integration with MCS provisioning.' },
        { id: 'horizon', name: 'Omnissa Horizon on AHV', products: ['Omnissa Horizon 8', 'AHV', 'Prism Central'], pitch: 'Keep Horizon, drop the VMware dependency.' },
      ],
    },

    {
      id: 'ndb',
      name: 'Database-as-a-Service (NDB)',
      short: 'NDB',
      products: ['Nutanix Database Service (SQL Server, Oracle, PostgreSQL + pgvector, MySQL/MariaDB, MongoDB)', 'NCI'],
      oneLiner: 'Turn database requests from days of DBA work into minutes of self-service — provisioning, cloning, patching and recovery automated across engines.',
      before: 'Days to provision a database, manual restores to give dev/test a copy, patching that falls behind, and DBAs buried in routine work.',
      after: 'Self-service provisioning with guardrails, space-efficient clones in minutes, fleet patching, and point-in-time recovery across on-prem and cloud.',
      capabilities: ['Self-service provisioning with standard profiles', 'Fast, space-efficient clones and refresh', 'Fleet patching', 'Point-in-time recovery and HA'],
      personas: {
        dba: 'NDB automates the toil — provisioning, cloning, patching, backup/restore — across SQL Server, Oracle, Postgres, MySQL and MongoDB so you can focus on performance and design.',
        exec: 'Developers get databases in minutes instead of days, and patching stops being a risk item.',
        platform: 'NDB has APIs and a Kubernetes operator so databases can be part of your pipelines.',
        finance: 'Space-efficient clones cut the storage cost of dev/test copies.',
      },
      proof: [
        { t: 'Snapshot and restore of a 40 TB database in under eight minutes; up to 9x storage savings reported.', src: S.ndb },
        { t: 'Provisioning a database cluster went from up to five days to under an hour.', src: S.ndb },
        { t: 'NDB 2.10 adds certified MongoDB Ops Manager integration and SQL Server/MySQL enhancements.', src: S.ndb210 },
      ],
      objections: [{ q: 'Our DBAs have scripts for this.', a: 'Scripts don’t give self-service, audit or consistent profiles. Use the NDB Fitment Tool to see which databases are good candidates.' }],
      nextSteps: ['Run the NDB Fitment Tool', 'DBA-focused demo: provision → clone → patch → restore', 'Pick a dev/test pilot'],
      editions: 'NDB is licensed per vCPU/engine — confirm counts.',
      editionsSrc: S.ndbFit,
      qualifiers: ['db.engines', 'db.provision'],
    },

    {
      id: 'nkp',
      name: 'Kubernetes & Platform Engineering (NKP)',
      short: 'NKP',
      products: ['Nutanix Kubernetes Platform (NKP)', 'Nutanix Data Services for Kubernetes (NDK)', 'NKP Metal (bare metal)', 'Files/Objects/Volumes CSI'],
      oneLiner: 'An enterprise Kubernetes platform that runs anywhere — on AHV, bare metal, other hypervisors and public cloud — with fleet management and GitOps built in.',
      before: 'Tanzu uncertainty or OpenShift cost, DIY clusters that each drift differently, and stateful apps with no good data-protection story.',
      after: 'Consistent, CNCF-conformant clusters managed as a fleet, integrated storage and data services, and one platform for both VMs and containers.',
      capabilities: ['Fleet management and GitOps', 'Runs on AHV, bare metal, other infra and public cloud', 'Integrated persistent storage and data services', 'Air-gapped deployments'],
      personas: {
        platform: 'NKP gives you pure upstream Kubernetes with fleet management, GitOps, observability and security built in — on AHV, bare metal (NKP Metal) or public cloud.',
        exec: 'One platform for today’s VMs and tomorrow’s containers, without betting on a single cloud.',
        infra: 'VM admins keep AHV; the platform team gets Kubernetes on the same infrastructure with Nutanix storage behind it.',
        finance: 'Tiered NKP editions let you start small and add fleet features as adoption grows.',
      },
      proof: [
        { t: 'NKP editions: Starter (Kubernetes on AHV), Pro (observability, backup, GPU, multi-platform), Ultimate (fleet management, GitOps, cost management, multitenancy).', src: S.nkp, verify: true },
        { t: 'NKP Metal extends NKP to bare metal for edge and AI workloads (GA expected 2H 2026).', src: S.platform26, verify: true },
      ],
      objections: [{ q: 'OpenShift is the standard.', a: 'Ask what they pay per core, how many of the OpenShift add-ons they use, and whether VM admins can operate VMs as Kubernetes objects.' }],
      nextSteps: ['Platform-engineering workshop', 'NKP demo: fleet + GitOps', 'Pilot on existing AHV or cloud'],
      editions: 'NKP Starter / Pro / Ultimate — map required features.',
      editionsSrc: S.nkp,
      qualifiers: ['k8s.stage', 'k8s.platform'],
    },

    {
      id: 'ai',
      name: 'Enterprise & Agentic AI',
      short: 'Enterprise AI',
      products: ['Nutanix Enterprise AI (NAI)', 'Nutanix Agent Gateway (incl. MCP Gateway)', 'Nutanix Agentic AI solution', 'NKP', 'Nutanix Objects for AI data', 'NVIDIA / AMD GPUs'],
      oneLiner: 'Run GenAI and agents on your data, under your control: private inferencing plus one governance layer for every model and agent — private or public.',
      before: 'Shadow AI tools, unpredictable token bills, sensitive data that can’t go to public APIs, and GPUs that are hard to share and govern.',
      after: 'A private inference endpoint with approved models, one gateway for policy, access and cost across public and private LLMs, and an AI stack on the same platform as everything else.',
      capabilities: ['Private model inferencing and fine-tuning', 'Unified policy, auth and rate-limiting for public + private LLMs', 'Secure agent access to tools/data (MCP gateway)', 'GPU resource sharing and governance'],
      personas: {
        exec: 'You get AI adoption without losing control of data, cost or risk — one governed front door for every model and agent.',
        ai: 'NAI serves approved models behind OpenAI-compatible endpoints with multi-GPU inference; Agent Gateway gives agents governed access to tools via MCP.',
        netsec: 'Every agent and model call goes through one gateway with authentication, observability and token-based rate limits.',
        platform: 'It all runs on NKP, so AI services follow the same GitOps and fleet practices as the rest of your apps.',
        finance: 'Token metering and rate limits make AI spend predictable; private inference avoids per-token cloud bills for high-volume use cases.',
      },
      proof: [
        { t: 'NAI: centralized fine-tuning and inferencing with resource management and governance across GPUs and other accelerators.', src: S.nai },
        { t: 'Nutanix Agent Gateway includes a GA MCP Gateway as a secure front door for agents to reach tools and data.', src: S.agentGw },
        { t: 'Nutanix Agentic AI full-stack solution announced March 2026 (GA expected 2H 2026 — verify).', src: S.agentic, verify: true },
      ],
      objections: [
        { q: 'We’ll just use the public cloud AI services.', a: 'Agent Gateway governs public models too; the question is which data and which volume justify private inference.' },
        { q: 'We don’t have GPUs.', a: 'Start with governance (Agent Gateway) on public models and plan private capacity as use cases prove out.' },
      ],
      nextSteps: ['AI use-case and data-sensitivity workshop', 'NAI / Agent Gateway demo', 'GPU sizing with the OEM'],
      editions: 'NAI licensing is separate — confirm GPU/node counts.',
      editionsSrc: S.nai,
      qualifiers: ['ai.stage', 'ai.data'],
      variants: [
        { id: 'private', name: 'Private GenAI & inferencing (NAI)', products: ['Nutanix Enterprise AI', 'NKP', 'GPUs'], pitch: 'Keep sensitive data on-prem with private model endpoints for RAG, assistants and document processing.' },
        { id: 'gov', name: 'AI governance & token cost control (Agent Gateway)', products: ['Nutanix Agent Gateway', 'MCP Gateway'], pitch: 'One governed front door for every model and agent — public or private — with auth, observability and rate limits.' },
      ],
    },
  ];

  F.playById = Object.fromEntries(F.plays.map((p) => [p.id, p]));
})(globalThis.Fivo = globalThis.Fivo || {});
