/* Fiv-o content: the discovery question bank, written in call order.

   The call runs in five phases (F.meta.phases) so it follows the customer's story:
     1 Why now        the event, the deadline, what happens if they miss it
     2 Environment    what they run today, in one uninterrupted pass
     3 Pain & cost    every pain, with its number captured on the spot
     4 Change & risk  intent to move, attachment, switching worries
     5 Decision       who signs, budget, process, how they buy, competition
   Within phases 2, 4 and 5, questions are asked in the order they appear in this file.
   In phases 1 and 3, the customer's top-ranked topic goes first.

   Question fields
     id, module (topic), phase (1–5), type ('single' | 'multi' | 'fields' | 'text'),
     text, short (report label)
     seq       order inside a phase before topic rank (phase 1: event → date → consequence)
     why / listen[] / probes[]   coaching layer
     when { any:[], all:[], not:[] }  terms are "questionId:optionId" or "questionId" (answered);
               a question may only depend on questions in its own or an earlier phase
     mustAsk   counts toward "must-asks left" for a 30-min call
     weight    1–3, how much a gap here matters for the next-call agenda
     ranked    multi-select where selection order = priority
     mp        MEDDPICC letter this question feeds (level 1 answered, 2 with a note)
     detail    placeholder for the note field (e.g., "Name / title")
     cost      [ask, unit] default "get the number" prompt for this question's pains
   Option fields
     signals { playId: n, 'playId.variantId': n }  (negative allowed)
     pain      a pain → Fiv-o asks for the number before moving on (phases 1 and 3 only)
     painLabel how the pain reads in the notes
     cost      [ask, unit] the question to ask for the number; unit ids are in F.meta.units
     flag      risk / landmine surfaced in the report
     tip       coaching response shown when selected
     mp        { LETTER: level } overrides the question-level MEDDPICC level
*/
(function (F) {
  'use strict';

  const o = (id, label, signals = {}, extra = {}) => ({ id, label, signals, ...extra });

  F.questions = [
    // ═════════════════════════ PHASE 1 · WHY NOW ═════════════════════════
    // What happened (seq 1), the date (seq 2–3), what happens if they miss it (seq 4).
    {
      id: 'trigger', module: 'why', phase: 1, seq: 0, type: 'multi', ranked: true, mustAsk: true, weight: 3,
      text: 'What prompted this conversation — why now?', short: 'Triggers',
      why: 'Everything downstream keys off the compelling event. No “why now” usually means no deal this year.',
      listen: ['A date (renewal, lease, EOL, audit)', 'A person who is under pressure', 'A recent incident'],
      probes: ['What happens if you do nothing for the next 12 months?', 'Why is this a priority now versus last year?', 'Who else in the business cares about this outcome?'],
      options: [
        o('vmware', 'VMware / Broadcom renewal or pricing', { vmw: 30 }),
        o('hardware', 'Hardware refresh or end-of-life', { refresh: 30, 'vmw.hci': 5 }),
        o('ops', 'IT team stretched / too complex', { ops: 30 }),
        o('resilience', 'DR gap, ransomware, audit or cyber-insurance', { dr: 20, cyber: 20 }),
        o('cloud', 'Cloud direction: DC exit, cloud cost, hybrid', { nc2: 30 }),
        o('storage', 'File / storage sprawl or backup target', { nus: 30 }),
        o('edge', 'Remote sites / branches', { edge: 30 }),
        o('ai', 'AI / GenAI initiative', { ai: 30 }),
        o('cost', 'Cost-reduction mandate or M&A consolidation', { vmw: 5, refresh: 10, ops: 10, nc2: 5 }),
        o('euc', 'VDI / desktops', { euc: 30 }),
        o('db', 'Databases / DBA workload', { ndb: 30 }),
        o('k8s', 'Containers / Kubernetes / app modernization', { nkp: 30 }),
        o('explore', 'Just exploring / partner brought us in', {}, { tip: 'No trigger yet — spend the call finding one. Ask about renewals, hardware age and the last outage.' }),
      ],
    },
    {
      id: 'res.event', module: 'resilience', phase: 1, seq: 1, type: 'multi', mustAsk: true, weight: 3,
      text: 'What’s driving the resilience conversation?', short: 'Resilience driver',
      why: 'Separates a DR (availability) story from a cyber (ransomware) story.',
      listen: ['An incident — theirs or a peer’s', 'Insurance questionnaire', 'Auditor language'],
      probes: ['What would a day of downtime cost the business?', 'What did the insurer or auditor ask for specifically?'],
      options: [
        o('ransomware', 'Ransomware hit us', { cyber: 25 }, { pain: true, painLabel: 'Ransomware incident', cost: ['What did it cost — days down, recovery spend, overtime?', 'usd'] }),
        o('peer', 'A peer or partner was hit', { cyber: 12 }),
        o('insurance', 'Cyber-insurance requirement', { cyber: 15 }, { pain: true, painLabel: 'Cyber-insurance requirements', cost: ['What happens to the premium or coverage if you can’t meet the requirements?', 'dpy'] }),
        o('audit', 'Audit finding', { cyber: 10, dr: 10 }, { pain: true, painLabel: 'Audit finding', cost: ['What does leaving the finding open cost — fines, re-audit, remediation hours?', 'usd'] }),
        o('faileddr', 'DR failed or was never tested', { dr: 20 }, { pain: true, painLabel: 'DR untested / failed', cost: ['If you had to fail over today, what would each day down cost?', 'dpd'] }),
        o('board', 'Board mandate', { cyber: 8, dr: 8 }),
        o('nosite', 'No DR site at all', { dr: 20, 'dr.cloud': 15 }, { pain: true, painLabel: 'No DR site', cost: ['What would a day without your main site cost the business?', 'dpd'] }),
      ],
    },
    {
      id: 'cloud.direction', module: 'cloud', phase: 1, seq: 1, type: 'multi', mustAsk: true, weight: 3,
      text: 'What’s the cloud direction?', short: 'Cloud direction',
      why: 'Each direction maps to a different NC2 (or on-prem) story.',
      listen: ['Datacenter lease end', '“Cloud was more expensive than we thought”'],
      probes: ['What’s worked and not worked in cloud so far?'],
      options: [
        o('exit', 'DC / colo exit', { nc2: 20, 'vmw.nc2': 10 }),
        o('repatriate', 'Cloud bills too high (repatriation)', { refresh: 10, nc2: 5, ops: 3 }, { pain: true, painLabel: 'Cloud costs above plan', cost: ['How far over plan is the cloud bill each month?', 'dpm'] }),
        o('burst', 'Burst for peaks', { nc2: 15 }),
        o('dr', 'DR in the cloud', { nc2: 10, dr: 10, 'dr.cloud': 15 }),
        o('expand', 'New region / expansion', { nc2: 12 }),
        o('mandate', 'Cloud-first mandate', { nc2: 12 }),
        o('hybrid', 'Hybrid by design', { nc2: 10 }),
      ],
    },
    {
      id: 'hw.what', module: 'hardware', phase: 1, seq: 1, type: 'multi', mustAsk: true, weight: 3,
      text: 'What’s coming due?', short: 'Refresh scope',
      why: 'Scope of the refresh sets deal size and which architecture fits.',
      listen: ['Everything at once (big opportunity)', 'Backup appliance refresh'],
      probes: ['What would you buy if you just repeated last time?'],
      options: [
        o('servers', 'Servers / compute', { refresh: 10 }),
        o('san', 'SAN / storage array', { refresh: 10, 'vmw.hci': 5, nus: 3 }),
        o('network', 'Network switches', { refresh: 3 }),
        o('backup', 'Backup appliance', { nus: 8, 'nus.objects': 8, dr: 3 }),
        o('all', 'All of it', { refresh: 15 }),
      ],
    },
    {
      id: 'cost.target', module: 'cost', phase: 1, seq: 1, type: 'single', weight: 2, mp: 'M',
      text: 'Is there a specific savings target?', short: 'Savings target', detail: 'Number (% or $)',
      why: 'A stated number becomes the success metric.',
      listen: ['Who set the number'],
      probes: ['What happens if you hit it — or miss it?'],
      options: [o('pct', 'Yes — a % target', {}, { mp: { M: 2 } }), o('usd', 'Yes — a $ target', {}, { mp: { M: 2 } }), o('dir', 'Directional only', {})],
    },
    {
      id: 'cost.levers', module: 'cost', phase: 1, seq: 1, type: 'multi', weight: 2,
      text: 'Where do they expect the savings to come from?', short: 'Savings levers',
      why: 'Maps the cost mandate onto the right play.',
      listen: ['Headcount freeze', 'Post-merger duplicate stacks'],
      probes: ['Which line item is the CFO looking at?'],
      options: [
        o('licensing', 'Software licensing', { vmw: 8 }),
        o('hardware', 'Hardware / footprint', { refresh: 8 }),
        o('cloud', 'Cloud spend', { nc2: 5, ops: 5 }),
        o('people', 'Team efficiency', { ops: 10 }),
        o('mna', 'Consolidation after M&A', { refresh: 5, ops: 5, vmw: 5 }),
      ],
    },
    {
      id: 'why.urgency', module: 'why', phase: 1, seq: 2, type: 'single', mustAsk: true, weight: 3, mp: 'DP',
      text: 'Is there a hard date driving this?', short: 'Compelling event', detail: 'What date / what happens then?',
      why: 'A date you can anchor a mutual plan to is the strongest compelling event.',
      listen: ['Contract or lease end dates', 'Fiscal year / budget deadlines', 'Board or audit commitments'],
      probes: ['What happens on that date if nothing has changed?', 'Who set that deadline?'],
      options: [
        o('renewal', 'Renewal / contract end (< 6 months)', {}, { mp: { DP: 2 } }),
        o('budget', 'Budget cycle / fiscal year', {}),
        o('eol', 'Hardware end of support', { refresh: 5 }),
        o('mandate', 'Audit, board or regulatory mandate', { cyber: 5 }),
        o('none', 'No hard date', {}, { mp: { DP: 0 }, tip: 'Create urgency: quantify the cost of waiting (renewal uplift, risk exposure, hours lost per month).' }),
      ],
    },
    {
      id: 'vmw.renewal', module: 'vmware', phase: 1, seq: 3, type: 'single', mustAsk: true, weight: 3, mp: 'DP',
      text: 'When does the current VMware term or support end?', short: 'VMware term ends', detail: 'Exact date',
      why: 'This is usually the compelling event and sets the mutual close plan.',
      listen: ['A short-term bridge already signed', 'Procurement lead times'],
      probes: ['What needs to happen internally before that date?', 'Would you consider a short bridge while you migrate?'],
      options: [
        o('lt3', 'Under 3 months', { vmw: 15 }, { mp: { DP: 2 }, tip: 'Tight: position a short bridge renewal plus a migration plan rather than a rushed cutover.' }),
        o('3to6', '3–6 months', { vmw: 20 }, { mp: { DP: 2 } }),
        o('6to12', '6–12 months', { vmw: 20 }, { mp: { DP: 2 } }),
        o('gt12', '12+ months', { vmw: 8 }),
        o('bridge', 'Just signed a 1-year bridge', { vmw: 20 }, { mp: { DP: 2 } }),
        o('lapsed', 'Already lapsed', { vmw: 15, cyber: 5 }, { tip: 'Lapsed support means no patches. Treat it as a security exposure and plan the move before the next audit.' }),
      ],
    },
    {
      id: 'hw.when', module: 'hardware', phase: 1, seq: 3, type: 'single', mustAsk: true, weight: 3, mp: 'DP',
      text: 'When does that gear go out of support?', short: 'Hardware EOL', detail: 'Date',
      why: 'The support end date is the compelling event for a refresh.',
      listen: ['Extended support costs', 'Supply-chain lead times'],
      probes: ['How long does procurement take on your side?'],
      options: [
        o('lt6', 'Under 6 months', { refresh: 10 }, { mp: { DP: 2 } }),
        o('6to12', '6–12 months', { refresh: 8 }, { mp: { DP: 2 } }),
        o('gt12', '12+ months', { refresh: 3 }),
        o('out', 'Already out of support', { refresh: 12 }, { tip: 'Out of support now: every failure is a gamble. Get the extended-support cost in Pain & cost.' }),
      ],
    },
    {
      id: 'cloud.deadline', module: 'cloud', phase: 1, seq: 3, type: 'single', weight: 2, mp: 'DP',
      text: 'Any hard date — colo contract or DC lease?', short: 'Cloud deadline', detail: 'Date',
      why: 'A lease end is a hard compelling event.',
      listen: ['Penalties for overrun'],
      probes: ['What happens if you miss it?'],
      options: [
        o('lt6', 'Under 6 months', { nc2: 5 }, { mp: { DP: 2 } }),
        o('6to12', '6–12 months', { nc2: 5 }, { mp: { DP: 2 } }),
        o('gt12', '12+ months', {}),
        o('none', 'None', {}),
      ],
    },
    {
      id: 'why.consequence', module: 'why', phase: 1, seq: 4, type: 'multi', mustAsk: true, weight: 3, mp: 'I', detail: 'Specifics',
      text: 'What happens if that date passes — or nothing changes?', short: 'If they miss it',
      why: 'The consequence of doing nothing is what makes the date real. No consequence, no urgency.',
      listen: ['Lost support or patches', 'A penalty or price jump', 'Who gets embarrassed if it slips'],
      probes: ['Who feels it first if this slips?', 'Has it slipped before? What happened?'],
      options: [
        o('support', 'Lose vendor support or security patches', { vmw: 5, refresh: 5, cyber: 3 }),
        o('price', 'A price jump or penalty', { vmw: 5, refresh: 3 }, { tip: 'Note it — you’ll get the dollar figure in Pain & cost, where it anchors the business case.' }),
        o('compliance', 'Compliance, audit or insurance exposure', { cyber: 5, dr: 3 }),
        o('outage', 'Outage or data-loss risk', { dr: 5, cyber: 3 }),
        o('projects', 'It blocks other projects', { ops: 3 }),
        o('leaders', 'Leadership or the board will ask why', {}),
        o('nothing', 'Nothing major — it’s a soft date', {}, { mp: { I: 0 }, tip: 'A soft date slips. Find a pain with a cost attached, or this moves to next year.' }),
      ],
    },

    // ═════════════════════════ PHASE 2 · ENVIRONMENT ═════════════════════════
    // One pass, in this order: platform → size → storage → servers → network →
    // sites and team → backup and DR → cloud → workloads. No pains here — those are phase 3.
    {
      id: 'env.hypervisor', module: 'env', phase: 2, type: 'multi', mustAsk: true, weight: 3,
      text: 'Which hypervisors run today?', short: 'Hypervisor(s)',
      why: 'vSphere opens the VMware topic; existing AHV means an expansion conversation.',
      listen: ['vSphere version (7 vs 8)', 'Hyper-V pilots — Microsoft may already be in the deal'],
      probes: ['What version are you on, and what’s the upgrade plan?'],
      options: [
        o('vsphere', 'VMware vSphere', { vmw: 15 }),
        o('hyperv', 'Hyper-V / Azure Local', { refresh: 5 }),
        o('ahv', 'Nutanix AHV (existing customer)', { vmw: -10, nus: 5, ndb: 5, nkp: 5, ops: 5 }, { tip: 'Existing customer: lead with expansion — NCM, NUS, NDB, NKP, DR — and check renewal timing.' }),
        o('kvm', 'Proxmox / KVM', { refresh: 5 }),
        o('physical', 'Mostly physical servers', { refresh: 10 }),
        o('cloudonly', 'Mostly public cloud', { nc2: 5 }),
      ],
    },
    {
      id: 'vmw.version', module: 'vmware', phase: 2, type: 'single', weight: 2,
      text: 'Which vSphere version are most hosts on?', short: 'vSphere version',
      why: 'Version tells you whether they’re already out of support and forced into Broadcom’s new licensing to upgrade.',
      listen: ['Hosts stuck on old versions', 'Extended support contracts'],
      probes: ['What’s blocking the upgrade?', 'Are you paying for extended support?'],
      options: [
        o('v6', '6.x or older', { vmw: 8, cyber: 3 }, { tip: 'Long out of support: patching and security exposure. Ask what’s blocking the upgrade.' }),
        o('v7', '7.x', { vmw: 8 }, { tip: 'vSphere 7 left general support in Oct 2025 — they’re on extended support or unsupported. Upgrading means Broadcom’s new licensing either way.' }),
        o('v8', '8.x', { vmw: 3 }, { tip: 'vSphere 8 general support ends Oct 2027 — a natural window to move instead of upgrading again.' }),
        o('v9', '9 / VCF 9', { vmw: 3 }),
        o('mixed', 'Mixed versions', { vmw: 3 }),
      ],
    },
    {
      id: 'vmw.license', module: 'vmware', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'What VMware licensing are you on — or being pushed to?', short: 'VMware license',
      why: 'Bundle and edition tell you what features they’re paying for and what they actually use.',
      listen: ['VCF bundle with components they don’t use', 'Core minimums', 'Lapsed support'],
      probes: ['What did Broadcom propose?', 'Which VCF components will you actually deploy?'],
      options: [
        o('vcf', 'VCF', { vmw: 10 }),
        o('vvf', 'VVF', { vmw: 10 }),
        o('std', 'vSphere Standard / Essentials Plus', { vmw: 10, ops: 3 }),
        o('perpetual', 'Legacy perpetual (support lapsing)', { vmw: 15 }, { tip: 'Perpetual with lapsing support: every unpatched month is exposure. Pair the migration plan with a short support bridge if needed.' }),
        o('cloud', 'VMware in cloud (VMC / AVS / GCVE)', { vmw: 10, 'vmw.nc2': 20, nc2: 10 }),
        o('unsure', 'Not sure yet', {}, { tip: 'Ask for the latest quote or partner proposal — it’s your best sizing and pain document.' }),
      ],
    },
    {
      id: 'env.counts', module: 'env', phase: 2, type: 'fields', weight: 2,
      text: 'Rough size of the estate?', short: 'Scale',
      why: 'Sizing inputs for Collector/Sizer and for qualifying deal size.',
      listen: ['Growth plans', 'Number of clusters vs hosts'],
      probes: ['Can you run Nutanix Collector or share an RVTools export?'],
      // Report prints "<value> <unit>" (unit defaults to the label), e.g. "180 VMs / 60 TB".
      fields: [
        { id: 'hosts', label: 'hosts' },
        { id: 'cores', label: 'cores' },
        { id: 'vms', label: 'VMs' },
        { id: 'tb', label: 'Storage', unit: 'TB' },
      ],
    },
    {
      id: 'env.storage', module: 'env', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'What storage sits under your virtualization today?', short: 'Primary storage',
      why: 'Decides full-stack HCI versus keep-your-array versus cloud landing.',
      listen: ['Array age and recent purchases', 'vSAN pain', 'Who owns storage'],
      probes: ['When was it bought and when does support end?', 'What do you like about it?'],
      options: [
        o('vsan', 'vSAN / HCI', { 'vmw.hci': 20, refresh: 5 }),
        o('san', 'SAN array (FC / iSCSI)', { 'vmw.ext': 12, refresh: 5 }),
        o('nas', 'NFS NAS', { 'vmw.hci': 5, 'vmw.ext': 3 }),
        o('local', 'Local disks / DAS', { 'vmw.hci': 10, refresh: 10 }),
        o('mix', 'A mix', { 'vmw.ext': 5, 'vmw.hci': 5 }),
      ],
    },
    {
      id: 'env.array.vendor', module: 'env', phase: 2, type: 'single', weight: 2,
      when: { any: ['env.storage:san', 'env.storage:mix'] },
      text: 'Which array is it?', short: 'Array vendor',
      why: 'Supported external arrays make “keep your array, change your hypervisor” possible.',
      listen: ['Recent purchase with years of support left', 'Frustration with the array vendor'],
      probes: ['Is the storage team happy with it?'],
      options: [
        o('everpure', 'Everpure (Pure) FlashArray', { 'vmw.ext': 12 }, { tip: 'Everpure FlashArray + NCI is GA (Dec 2025) with Prism-integrated VM snapshots and SafeMode.' }),
        o('powerflex', 'Dell PowerFlex', { 'vmw.ext': 12 }),
        o('powerstore', 'Dell PowerStore', { 'vmw.ext': 12 }, { tip: 'PowerStore is supported with NCI 7.6 (July 2026) — confirm the model and version on the compatibility list.' }),
        o('netapp', 'NetApp ONTAP (AFF / FAS)', { 'vmw.ext': 8 }, { tip: 'ONTAP support announced for 2H 2026 — verify GA before committing.' }),
        o('lenovo', 'Lenovo ThinkSystem', { 'vmw.ext': 6 }, { tip: 'Lenovo ThinkSystem storage announced at .NEXT 2026 — verify.' }),
        o('other', 'Other (HPE, Hitachi, IBM, Dell Unity/PowerMax…)', { 'vmw.hci': 8, refresh: 3 }),
      ],
    },
    {
      id: 'env.array.age', module: 'env', phase: 2, type: 'single', weight: 2,
      when: { any: ['env.storage:san', 'env.storage:mix'] },
      text: 'How old is the array / when does support end?', short: 'Array age',
      why: 'A recent array argues for external storage; an aging one argues for HCI and opens the refresh play.',
      listen: ['Upcoming maintenance renewal', 'Capacity running out'],
      probes: ['What’s the next storage spend you already see coming?'],
      options: [
        o('new', 'Under 3 years', { 'vmw.ext': 15 }),
        o('mid', '3–5 years', { 'vmw.ext': 5, 'vmw.hci': 5 }),
        o('old', 'Over 5 years / support ending', { 'vmw.hci': 15, refresh: 10 }, { tip: 'The next maintenance quote is a big number. Note it — you’ll ask for it in Pain & cost.' }),
      ],
    },
    {
      id: 'env.servers', module: 'env', phase: 2, type: 'single', mustAsk: true, weight: 2,
      text: 'How old are the servers — and are they still under warranty?', short: 'Server age',
      why: 'Server age sets the refresh window and whether you reuse hardware or start clean.',
      listen: ['Warranty or support end dates', 'Recently purchased hosts'],
      probes: ['When does the oldest host come off warranty?', 'What’s the refresh plan for them?'],
      options: [
        o('new', 'Under 3 years', { 'vmw.ext': 3 }, { tip: 'Recent servers may be reusable — check them against the Nutanix hardware compatibility list.' }),
        o('mid', '3–5 years, still under warranty', { refresh: 3 }),
        o('old', '5+ years, or warranty ending soon', { refresh: 10, 'vmw.hci': 5 }),
        o('out', 'Out of warranty', { refresh: 12, 'vmw.hci': 5 }),
        o('mixed', 'A mix of ages', { refresh: 3 }),
      ],
    },
    {
      id: 'hw.arch', module: 'hardware', phase: 2, type: 'single', weight: 2,
      text: 'How is it built today?', short: 'Architecture',
      why: 'Three-tier and converged stacks are the classic HCI consolidation story.',
      listen: ['Many vendors to manage', 'Existing HCI they’re unhappy with'],
      probes: ['Who do you call when something breaks?'],
      options: [
        o('3tier', '3-tier: servers + SAN + switches', { refresh: 15, 'vmw.hci': 5 }),
        o('vsan', 'HCI on vSAN', { 'vmw.hci': 10 }),
        o('hcio', 'Other HCI (SimpliVity, Scale, Azure Local…)', { refresh: 10 }),
        o('ci', 'Converged (VxBlock, FlexPod)', { refresh: 12 }),
        o('physical', 'Mostly physical servers', { refresh: 10 }),
      ],
    },
    {
      id: 'vmw.nsx', module: 'vmware', phase: 2, type: 'single', weight: 2,
      text: 'How much NSX do you use?', short: 'NSX usage',
      why: 'Heavy NSX overlay use is a technical landmine; DFW-only maps cleanly to Flow Network Security.',
      listen: ['Overlay networks', 'NSX load balancers or edges', 'Security team ownership'],
      probes: ['Who owns NSX policy today?'],
      options: [
        o('none', 'None', {}),
        o('dfw', 'DFW / microsegmentation only', { cyber: 5, vmw: 3 }),
        o('overlay', 'Overlay networking, edges, load balancing', {}, { flag: 'Heavy NSX overlay use — validate Flow Virtual Networking parity with a specialist before committing.' }),
        o('unsure', 'Not sure', {}),
      ],
    },
    {
      id: 'vmw.addons', module: 'vmware', phase: 2, type: 'multi', weight: 2,
      text: 'Which other VMware products are in play?', short: 'VMware add-ons',
      why: 'Each add-on maps to another Nutanix play and to a migration dependency.',
      listen: ['Horizon renewal tied to vSphere', 'SRM runbooks', 'Tanzu projects on hold'],
      probes: ['What do you use Aria for day to day?'],
      options: [
        o('horizon', 'Horizon (VDI)', { euc: 25, 'euc.horizon': 20 }),
        o('aria', 'Aria / vROps', { ops: 12 }),
        o('srm', 'Site Recovery Manager', { dr: 15, 'dr.site': 10 }),
        o('tanzu', 'Tanzu / VKS', { nkp: 20 }),
        o('none', 'None', {}),
      ],
    },
    {
      id: 'env.sites', module: 'env', phase: 2, type: 'single', weight: 1,
      text: 'How many locations run IT infrastructure?', short: 'Sites',
      why: 'Six or more sites opens the ROBO/edge play.',
      listen: ['Sites with no IT staff', 'Acquired locations'],
      probes: ['What runs at the sites versus HQ?'],
      options: [
        o('s1', 'One site', {}),
        o('s2', '2–5 sites', { dr: 3 }),
        o('s6', '6–20 sites', { edge: 15 }),
        o('s20', '20+ sites', { edge: 25 }),
      ],
    },
    {
      id: 'edge.staff', module: 'env', phase: 2, type: 'single', mustAsk: true, weight: 3,
      when: { any: ['env.sites:s2', 'env.sites:s6', 'env.sites:s20'] },
      text: 'Is there IT staff at the other sites?', short: 'Site staff',
      why: 'No local IT staff is the core remote-site pain — and tells you how the team is spread.',
      listen: ['Store managers rebooting servers', 'Drive time'],
      probes: ['What happens when a site server fails?'],
      options: [
        o('none', 'None', { edge: 10 }, { tip: 'Every site problem means travel or remote hands. Note it — you’ll get the hours in Pain & cost.' }),
        o('some', 'At some sites', { edge: 5 }),
        o('yes', 'Yes, everywhere', {}),
      ],
    },
    {
      id: 'edge.apps', module: 'edge', phase: 2, type: 'multi', weight: 2,
      text: 'What runs at the sites?', short: 'Site apps',
      why: 'Site workloads set cluster size and may open AI/NKP at the edge.',
      listen: ['POS, clinical, OT systems', 'Video / computer vision'],
      probes: ['Which of those can’t go down?'],
      options: [
        o('pos', 'POS / retail systems', { edge: 5 }),
        o('clinical', 'Clinical / healthcare', { edge: 5 }),
        o('ot', 'Manufacturing / OT', { edge: 5 }),
        o('fileprint', 'File & print', { edge: 3, 'nus.files': 3 }),
        o('vdi', 'VDI', { euc: 5 }),
        o('ai', 'AI / computer vision', { ai: 8, nkp: 5 }),
      ],
    },
    {
      id: 'edge.today', module: 'edge', phase: 2, type: 'single', weight: 1,
      text: 'What infrastructure sits at each site?', short: 'Site infrastructure',
      why: 'Current per-site gear sets the replacement footprint.',
      listen: ['vSAN ROBO licensing', 'Single points of failure'],
      probes: ['What does a site kit cost you today?'],
      options: [
        o('small3', '2–3 servers + small SAN/NAS', { edge: 8 }),
        o('vsanrobo', 'vSAN ROBO', { edge: 5, vmw: 5 }),
        o('single', 'A single server', { edge: 8 }),
        o('cloudonly', 'Cloud-only', {}),
        o('mixed', 'Mixed', { edge: 3 }),
      ],
    },
    {
      id: 'edge.conn', module: 'edge', phase: 2, type: 'single', weight: 1,
      text: 'How reliable is site connectivity?', short: 'Site connectivity',
      why: 'Intermittent WAN means local resilience matters.',
      listen: ['Outages during storms', 'Air-gapped sites'],
      probes: ['What happens at the site when the WAN drops?'],
      options: [o('reliable', 'Reliable WAN', {}), o('intermittent', 'Intermittent', { edge: 5 }), o('airgap', 'Air-gapped', { edge: 5, nkp: 3 })],
    },
    {
      id: 'env.itteam', module: 'env', phase: 2, type: 'single', mustAsk: true, weight: 2,
      text: 'How big is the team that runs infrastructure?', short: 'IT team',
      why: 'Team size sets the story: small teams buy simplicity and time back; big teams buy automation and self-service.',
      listen: ['Generalists wearing many hats', 'Key-person risk (“only Dave knows vSAN”)', 'Open headcount they can’t fill'],
      probes: ['What does a typical week look like for the team?', 'What would you do with an extra day a week?'],
      options: [
        o('t1', '1–2 people', { ops: 15, refresh: 5 }),
        o('t2', '3–5 people', { ops: 10 }),
        o('t3', '6–15 people', { ops: 3 }),
        o('t4', '16+ people', { nkp: 3, ndb: 3 }),
      ],
    },
    {
      id: 'env.backup', module: 'env', phase: 2, type: 'single', weight: 2,
      text: 'What do you back up with?', short: 'Backup',
      why: 'Confirms AHV support and opens the immutability / Objects conversation.',
      listen: ['No immutable copy', 'Backup vendor up for renewal'],
      probes: ['When did you last do a full restore test?'],
      options: [
        o('veeam', 'Veeam', {}),
        o('commvault', 'Commvault', {}),
        o('rubrik', 'Rubrik / Cohesity', {}),
        o('hycu', 'HYCU', {}),
        o('other', 'Other / legacy', { dr: 3 }),
        o('none', 'Nothing consistent', { dr: 10, cyber: 10 }, { tip: 'Recovery depends on luck. Note it — you’ll put a cost on it in Pain & cost.' }),
      ],
    },
    {
      id: 'res.dr', module: 'resilience', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'What does DR look like today?', short: 'Current DR',
      why: 'Current state determines second-site versus cloud DR.',
      listen: ['SRM/Zerto cost', 'Manual runbooks'],
      probes: ['When did you last do a full failover test?'],
      options: [
        o('none', 'None — backups only', { dr: 15, 'dr.cloud': 15 }),
        o('srm', 'Second site with SRM / Zerto', { dr: 10, 'dr.site': 15 }),
        o('manual', 'Second site, manual recovery', { dr: 12, 'dr.site': 10 }),
        o('draas', 'DRaaS / cloud DR', { dr: 5, 'dr.cloud': 10 }),
        o('offsite', 'Offsite backup copies only', { dr: 12, 'dr.cloud': 10 }),
      ],
    },
    {
      id: 'res.site2', module: 'resilience', phase: 2, type: 'single', weight: 2,
      when: { any: ['res.dr:none', 'res.dr:offsite'] },
      text: 'Do you have — or want — a second location?', short: 'Second site',
      why: 'No second site and no appetite for one makes cloud DR the answer.',
      listen: ['A branch office with space', 'Colo contracts'],
      probes: ['What would a second site cost you to stand up?'],
      options: [
        o('owned', 'We own a second DC / colo', { 'dr.site': 15 }),
        o('branch', 'Could use a branch site', { 'dr.site': 10, edge: 3 }),
        o('cloud', 'No — prefer cloud', { 'dr.cloud': 20, nc2: 10 }),
        o('no', 'No second site', { 'dr.cloud': 10 }),
      ],
    },
    {
      id: 'res.rpo', module: 'resilience', phase: 2, type: 'single', weight: 3, mp: 'DC',
      text: 'What recovery targets do tier-1 apps need?', short: 'RPO / RTO', detail: 'Which apps?',
      why: 'RPO/RTO drives the replication mode and licensing tier.',
      listen: ['“Zero data loss” (probe distance and latency)', 'Unknown targets'],
      probes: ['Which three apps would you recover first?'],
      options: [
        o('hours', 'Hours to days (backup is fine)', { dr: 5 }),
        o('lt1h', 'Under an hour', { dr: 10 }),
        o('zero', 'Near-zero (sync / metro)', { dr: 15, 'dr.site': 10 }, { tip: 'Sync/Metro needs low latency between sites (roughly ≤5 ms RTT) — check the distance.' }),
        o('unknown', 'Not defined', { dr: 5 }, { tip: 'Offer a short DR workshop to define tiers — it’s a great next step.' }),
      ],
    },
    {
      id: 'res.files', module: 'resilience', phase: 2, type: 'single', weight: 2,
      text: 'How much sensitive data sits on file shares?', short: 'File-share exposure',
      why: 'Unstructured data is where ransomware does the most damage — Data Lens + Files.',
      listen: ['Department shares', 'PII / PHI on shares'],
      probes: ['Who can see who accessed what?'],
      options: [
        o('lots', 'A lot (TBs of department / user shares)', { cyber: 8, 'nus.files': 10 }),
        o('some', 'Some', { cyber: 3 }),
        o('little', 'Very little', {}),
      ],
    },
    {
      id: 'env.cloud', module: 'env', phase: 2, type: 'multi', weight: 1,
      text: 'Public cloud footprint?', short: 'Cloud',
      why: 'VMware-in-cloud (VMC/AVS/GCVE) is a strong NC2 landing signal.',
      listen: ['Cloud commits to burn down', 'Cost surprises'],
      probes: ['Who owns the cloud budget?'],
      options: [
        o('none', 'None / M365 only', {}),
        o('aws', 'AWS', { nc2: 5 }),
        o('azure', 'Azure', { nc2: 5 }),
        o('gcp', 'Google Cloud', { nc2: 5 }),
        o('vmc', 'VMware in cloud (VMC / AVS / GCVE)', { nc2: 15, 'vmw.nc2': 25, vmw: 10 }),
      ],
    },
    {
      id: 'stor.types', module: 'storage', phase: 2, type: 'multi', mustAsk: true, weight: 3,
      text: 'What unstructured data are we talking about?', short: 'Data types',
      why: 'Files versus objects decides the NUS variant.',
      listen: ['Windows file servers', 'NAS filer renewal', 'Backup repository needs'],
      probes: ['What’s growing fastest?'],
      options: [
        o('fileservers', 'Windows file servers', { nus: 15, 'nus.files': 15 }),
        o('nas', 'NAS filer (NetApp, Isilon/PowerScale…)', { nus: 15, 'nus.files': 12 }),
        o('backup', 'Backup target / repository', { nus: 12, 'nus.objects': 20 }),
        o('imaging', 'Imaging, video, archives', { nus: 10, 'nus.objects': 10 }),
        o('ai', 'Analytics / AI datasets', { nus: 8, 'nus.objects': 10, ai: 5 }),
        o('profiles', 'User profiles / home dirs (VDI)', { 'nus.files': 8, euc: 5 }),
      ],
    },
    {
      id: 'stor.size', module: 'storage', phase: 2, type: 'single', weight: 1,
      text: 'How much capacity?', short: 'Capacity',
      why: 'NUS is licensed per TiB — sizing input.',
      listen: ['Cold data that could tier'],
      probes: ['How much of it is actually touched each month?'],
      options: [o('lt50', 'Under 50 TB', {}), o('50to250', '50–250 TB', {}), o('250to1p', '250 TB – 1 PB', {}), o('gt1p', 'Over 1 PB', {})],
    },
    {
      id: 'stor.growth', module: 'storage', phase: 2, type: 'single', weight: 1,
      text: 'How fast is it growing?', short: 'Growth',
      why: 'Fast growth makes scale-out economics matter.',
      listen: ['New data sources (imaging, video, AI)'],
      probes: ['What’s driving the growth?'],
      options: [
        o('lt10', 'Under 10% a year', {}),
        o('10to30', '10–30% a year', { nus: 3 }),
        o('gt30', 'Over 30% a year', { nus: 5 }),
      ],
    },
    {
      id: 'euc.platform', module: 'euc', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'Which VDI platform?', short: 'VDI platform',
      why: 'Citrix versus Horizon decides the variant; AVD/W365 may be a cloud play.',
      listen: ['Horizon renewal tied to vSphere', 'Citrix licensing changes'],
      probes: ['Is the broker decision separate from the hypervisor decision?'],
      options: [
        o('citrix', 'Citrix (CVAD / DaaS)', { euc: 10, 'euc.citrix': 25 }),
        o('horizon', 'Omnissa Horizon', { euc: 12, 'euc.horizon': 25 }),
        o('avd', 'Microsoft AVD / W365', { euc: 3 }),
        o('physical', 'Physical PCs only', { euc: 5 }),
        o('other', 'Other', { euc: 3 }),
      ],
    },
    {
      id: 'euc.users', module: 'euc', phase: 2, type: 'single', weight: 1,
      text: 'How many users?', short: 'VDI users',
      why: 'Sizing and deal size.',
      listen: ['Seasonal peaks', 'Contractors'],
      probes: ['How many concurrent at peak?'],
      options: [o('lt250', 'Under 250', {}), o('250to1k', '250–1,000', {}), o('1kto5k', '1,000–5,000', {}), o('gt5k', '5,000+', {})],
    },
    {
      id: 'euc.type', module: 'euc', phase: 2, type: 'single', weight: 1,
      text: 'Persistent or non-persistent desktops?', short: 'Desktop type',
      why: 'Drives storage sizing and clone strategy.',
      listen: ['Profile management pain'],
      probes: ['How do you handle profiles today?'],
      options: [o('nonpersist', 'Non-persistent', {}), o('persist', 'Persistent', {}), o('mix', 'Mix', {})],
    },
    {
      id: 'euc.gpu', module: 'euc', phase: 2, type: 'single', weight: 1,
      text: 'Any GPU / graphics users?', short: 'VDI GPU',
      why: 'GPU desktops change node selection.',
      listen: ['CAD, imaging, engineering'],
      probes: ['Which apps need GPU?'],
      options: [o('yes', 'Yes (CAD / graphics)', {}), o('some', 'Some', {}), o('no', 'No', {})],
    },
    {
      id: 'db.engines', module: 'db', phase: 2, type: 'multi', mustAsk: true, weight: 3,
      text: 'Which database engines?', short: 'DB engines',
      why: 'NDB supports SQL Server, Oracle, PostgreSQL (incl. pgvector), MySQL/MariaDB and MongoDB.',
      listen: ['SQL Server sprawl', 'Oracle licensing sensitivity'],
      probes: ['Which engine causes the most tickets?'],
      options: [
        o('mssql', 'SQL Server', { ndb: 8 }), o('oracle', 'Oracle', { ndb: 8 }), o('pg', 'PostgreSQL', { ndb: 8 }),
        o('mysql', 'MySQL / MariaDB', { ndb: 6 }), o('mongo', 'MongoDB', { ndb: 6 }), o('other', 'Other', {}),
      ],
    },
    {
      id: 'db.count', module: 'db', phase: 2, type: 'single', weight: 2,
      text: 'How many database instances?', short: 'DB instances',
      why: 'Fleet size decides whether automation pays off.',
      listen: ['Dev/test copies multiplying'],
      probes: ['How many of those are copies of production?'],
      options: [o('lt25', 'Under 25', {}), o('25to100', '25–100', { ndb: 5 }), o('100to500', '100–500', { ndb: 12 }), o('gt500', '500+', { ndb: 18 })],
    },
    {
      id: 'db.dbas', module: 'db', phase: 2, type: 'single', weight: 1,
      text: 'How many DBAs?', short: 'DBAs',
      why: 'Few DBAs + many databases = strong NDB fit.',
      listen: ['Sysadmins doing DBA work'],
      probes: ['What do the DBAs spend most time on?'],
      options: [o('0to1', '0–1 (sysadmin does it)', { ndb: 5 }), o('2to3', '2–3', { ndb: 3 }), o('4to10', '4–10', {}), o('gt10', '10+', {})],
    },
    {
      id: 'k8s.stage', module: 'k8s', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'Where are you with containers / Kubernetes?', short: 'K8s maturity',
      why: 'Maturity decides whether to lead with NKP or park it.',
      listen: ['Pilot projects without a platform team'],
      probes: ['Which apps are running in containers today?'],
      options: [
        o('none', 'None yet', { nkp: 3 }),
        o('exp', 'Experimenting', { nkp: 10 }),
        o('some', 'Some production', { nkp: 15 }),
        o('broad', 'Broad production', { nkp: 15 }),
      ],
    },
    {
      id: 'k8s.platform', module: 'k8s', phase: 2, type: 'multi', weight: 2,
      text: 'What Kubernetes platform(s)?', short: 'K8s platform',
      why: 'Incumbent platform sets the competitive angle.',
      listen: ['OpenShift cost', 'Tanzu uncertainty'],
      probes: ['What do you pay per core today?'],
      options: [
        o('openshift', 'OpenShift', { nkp: 10 }), o('tanzu', 'Tanzu / VKS', { nkp: 15, vmw: 5 }), o('rancher', 'Rancher', { nkp: 8 }),
        o('cloud', 'EKS / AKS / GKE', { nkp: 5, nc2: 3 }), o('diy', 'DIY (kubeadm etc.)', { nkp: 12 }), o('none', 'None', {}),
      ],
    },
    {
      id: 'k8s.team', module: 'k8s', phase: 2, type: 'single', weight: 1,
      text: 'Who runs Kubernetes?', short: 'K8s owner',
      why: 'No platform team means they need an opinionated, managed platform.',
      listen: ['Developers running clusters'],
      probes: ['Who gets paged when a cluster breaks?'],
      options: [o('platform', 'Dedicated platform team', {}), o('ops', 'Shared ops team', { nkp: 5, ops: 3 }), o('devs', 'Developers', { nkp: 5 })],
    },
    {
      id: 'k8s.stateful', module: 'k8s', phase: 2, type: 'single', weight: 1,
      text: 'Stateful workloads on Kubernetes?', short: 'Stateful apps',
      why: 'Stateful apps need data services (NDK, CSI, backup).',
      listen: ['Databases in containers'],
      probes: ['How do you back them up?'],
      options: [o('stateless', 'Mostly stateless', {}), o('stateful', 'Significant stateful (DBs, queues)', { nkp: 8 })],
    },
    {
      id: 'k8s.where', module: 'k8s', phase: 2, type: 'multi', weight: 1,
      text: 'Where does Kubernetes need to run?', short: 'K8s locations',
      why: 'NKP runs on AHV, bare metal, other infra, public cloud and air-gapped.',
      listen: ['Edge', 'Air-gapped'],
      probes: ['Do you need one policy across all of them?'],
      options: [o('onprem', 'On-prem', {}), o('cloud', 'Public cloud', { nkp: 3 }), o('edge', 'Edge', { nkp: 8, edge: 5 }), o('airgap', 'Air-gapped', { nkp: 10 })],
    },
    {
      id: 'ai.stage', module: 'ai', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'Where are you with AI?', short: 'AI stage',
      why: 'Stage decides private inference versus governance-first.',
      listen: ['Shadow ChatGPT/Copilot use', 'A named pilot'],
      probes: ['What’s the first use case the business asked for?'],
      options: [
        o('curious', 'Curious / no plan', { ai: 3 }),
        o('public', 'Using public GenAI tools', { ai: 8, 'ai.gov': 10 }),
        o('pilots', 'Pilots / POCs', { ai: 15, 'ai.private': 10 }),
        o('prod', 'Production workloads', { ai: 20 }),
        o('agents', 'Building agents', { ai: 20, 'ai.gov': 15 }),
      ],
    },
    {
      id: 'ai.usecases', module: 'ai', phase: 2, type: 'multi', weight: 2,
      text: 'Which use cases?', short: 'AI use cases',
      why: 'Use cases decide model, data and GPU needs.',
      listen: ['Internal knowledge search (RAG)', 'Agentic workflows'],
      probes: ['How will you measure whether it worked?'],
      options: [
        o('rag', 'Internal knowledge chat / RAG', { 'ai.private': 10 }),
        o('support', 'Customer support', { ai: 5 }),
        o('code', 'Code assist', { ai: 3 }),
        o('docs', 'Document processing', { 'ai.private': 5 }),
        o('agents', 'Agentic workflows', { 'ai.gov': 10 }),
        o('vision', 'Vision / edge inference', { edge: 5, nkp: 3 }),
      ],
    },
    {
      id: 'ai.data', module: 'ai', phase: 2, type: 'single', mustAsk: true, weight: 3,
      text: 'Can the data go to public LLM APIs?', short: 'AI data sensitivity',
      why: 'Data that can’t leave is the strongest private-inference signal.',
      listen: ['Regulated data (PHI, PII, CUI)', 'Legal blocking tools'],
      probes: ['Who decides what data AI tools can touch?'],
      options: [
        o('no', 'No — must stay private', { ai: 15, 'ai.private': 20 }),
        o('some', 'Some can, some can’t', { ai: 8, 'ai.gov': 10 }),
        o('yes', 'Yes, all fine', { 'ai.gov': 5 }),
      ],
    },
    {
      id: 'ai.gpu', module: 'ai', phase: 2, type: 'single', weight: 2,
      text: 'GPU situation?', short: 'GPUs',
      why: 'GPUs on order or idle GPUs are an immediate NAI opportunity.',
      listen: ['Idle GPUs', 'Long lead times'],
      probes: ['Who decides where GPUs go?'],
      options: [
        o('none', 'None', {}),
        o('have', 'Have some', { ai: 10, 'ai.private': 5 }),
        o('planning', 'Ordered / planning', { ai: 10 }),
        o('cloud', 'Cloud GPUs only', { 'ai.gov': 5, nc2: 3 }),
      ],
    },

    // ═════════════════════════ PHASE 3 · PAIN & COST ═════════════════════════
    // Grouped by topic, top-ranked topic first. Every pain asks for its number on the spot.
    {
      id: 'vmw.price', module: 'vmware', phase: 3, type: 'single', mustAsk: true, weight: 2,
      text: 'What did the renewal do to cost?', short: 'Renewal impact', detail: 'Quote amount, if shared',
      why: 'Quantifies the pain and sets the TCO baseline.',
      listen: ['Unbudgeted spend', 'Who had to approve it'],
      probes: ['What did that do to the rest of this year’s budget?', 'Who had to sign off on the increase?'],
      cost: ['What’s the increase in dollars per year?', 'dpy'],
      options: [
        o('noquote', 'No quote yet', {}),
        o('lt50', 'Up less than 50%', { vmw: 5 }),
        o('2to3', 'Roughly 2–3x', { vmw: 15 }, { pain: true, painLabel: 'VMware renewal quoted ~2–3x' }),
        o('gt3', 'More than 3x', { vmw: 20 }, { pain: true, painLabel: 'VMware renewal quoted >3x' }),
        o('bundle', 'Forced into a bundle we don’t need', { vmw: 15 }, { pain: true, painLabel: 'Forced into VMware bundle' }),
      ],
    },
    {
      id: 'hw.pain', module: 'hardware', phase: 3, type: 'multi', mustAsk: true, weight: 2,
      text: 'What hurts about the current gear?', short: 'Hardware pain',
      why: 'Refresh pain beyond “it’s old” is what differentiates the architecture choice.',
      listen: ['Firmware compatibility matrices', 'Rack space / power limits'],
      probes: ['What did the last upgrade cost you in time?'],
      cost: ['What does that cost — hours a month or dollars a year?', 'hpm'],
      options: [
        o('upgrades', 'Complex upgrades / firmware', { ops: 8, refresh: 8 }, { pain: true, cost: ['How many hours a month go to firmware and hardware upgrades?', 'hpm'] }),
        o('perf', 'Performance', { refresh: 5 }, { pain: true, cost: ['How many people feel the slowdown, and how often?', 'people'] }),
        o('capacity', 'Capacity', { refresh: 5, nus: 3 }, { pain: true, cost: ['What did the last emergency capacity purchase cost?', 'usd'] }),
        o('maint', 'Maintenance / extended-support cost', { refresh: 8 }, { pain: true, cost: ['What’s the next maintenance or extended-support quote?', 'dpy'] }),
        o('supply', 'Supply-chain lead times', { refresh: 5 }, { pain: true, cost: ['How long do orders take to arrive?', 'days'] }),
        o('power', 'Power, space, cooling', { refresh: 8 }, { pain: true, cost: ['What do power, cooling and rack space cost a year?', 'dpy'] }),
        o('support', 'Vendor support quality', { refresh: 5 }, { pain: true, cost: ['How many hours a month go to chasing vendor support?', 'hpm'] }),
      ],
    },
    {
      id: 'ops.upgrades', module: 'ops', phase: 3, type: 'single', mustAsk: true, weight: 3,
      text: 'How painful are upgrades and patching (firmware, hypervisor, storage)?', short: 'Upgrades',
      why: 'Upgrade pain is the most common commercial pain and the best LCM demo.',
      listen: ['Weekend maintenance', 'Falling behind on patches', 'An outage caused by an upgrade'],
      probes: ['When was the last upgrade and how long did it take?', 'What’s the oldest version still running?'],
      options: [
        o('easy', 'Routine and easy', {}),
        o('weekends', 'Weekend maintenance windows', { ops: 10 }, { pain: true, painLabel: 'Upgrades need weekend maintenance windows', cost: ['How many hours does each window take, times the people on it, per month?', 'hpm'] }),
        o('behind', 'We fall behind / skip them', { ops: 12, cyber: 5 }, { pain: true, painLabel: 'Patching falls behind', cost: ['How many hours a month would it take to stay current?', 'hpm'] }),
        o('outage', 'An upgrade caused an outage', { ops: 12, refresh: 5 }, { pain: true, painLabel: 'Upgrade-caused outage', cost: ['What did the outage cost — hours down, overtime, lost business?', 'usd'] }),
      ],
    },
    {
      id: 'ops.hours', module: 'ops', phase: 3, type: 'single', weight: 2,
      text: 'How much of the team’s week goes to keeping the lights on?', short: 'KTLO time',
      why: 'Turns “we’re busy” into hours you can put in a business case.',
      listen: ['Projects stuck in backlog'],
      probes: ['What project would you start if you got that time back?'],
      cost: ['Roughly how many hours a week is that, across the team?', 'hpw'],
      options: [
        o('lt10', 'Under 10%', {}),
        o('10to30', '10–30%', { ops: 5 }),
        o('30to50', '30–50%', { ops: 10 }, { pain: true, painLabel: '30–50% of team time on keeping the lights on' }),
        o('gt50', 'Over 50%', { ops: 15 }, { pain: true, painLabel: 'Over half of team time on keeping the lights on' }),
      ],
    },
    {
      id: 'ops.selfservice', module: 'ops', phase: 3, type: 'single', weight: 1,
      text: 'How long do app teams wait for a new VM?', short: 'VM turnaround',
      why: 'Long waits mean shadow IT and a self-service story.',
      listen: ['Tickets and approvals', 'Developers going to public cloud'],
      probes: ['What happens when they can’t wait?'],
      cost: ['How many requests a month, and how many team hours does each one take?', 'hpm'],
      options: [
        o('minutes', 'Minutes (self-service)', {}),
        o('days', 'Days', { ops: 8 }, { pain: true, painLabel: 'Days to provision a VM' }),
        o('weeks', 'Weeks', { ops: 12, nkp: 3 }, { pain: true, painLabel: 'Weeks to provision a VM' }),
      ],
    },
    {
      id: 'ops.capacity', module: 'ops', phase: 3, type: 'single', weight: 1,
      text: 'How do you know when you’ll run out of capacity?', short: 'Capacity planning',
      why: 'Capacity blind spots lead to over-buying or emergencies — NCM runway fixes both.',
      listen: ['Spreadsheets', 'Emergency purchases'],
      probes: ['When did you last get surprised by capacity?'],
      options: [
        o('tool', 'Forecasting tool', {}),
        o('manual', 'Spreadsheets / gut feel', { ops: 6 }, { pain: true, painLabel: 'Capacity planned by spreadsheet or gut feel', cost: ['How many hours a month go into capacity spreadsheets?', 'hpm'] }),
        o('surprise', 'We find out when it’s full', { ops: 10 }, { pain: true, painLabel: 'No capacity forecasting — surprises', cost: ['What did the last surprise cost — the rush purchase, overtime, downtime?', 'usd'] }),
      ],
    },
    {
      id: 'ops.consoles', module: 'ops', phase: 3, type: 'single', weight: 1,
      text: 'How many tools or consoles does it take to run the stack?', short: 'Consoles',
      why: 'Tool sprawl is the simplest “one console” proof point.',
      listen: ['Separate storage, network and backup UIs'],
      probes: ['Walk me through what you touch to add a VM with storage and a network.'],
      options: [
        o('few', '1–2', {}),
        o('some', '3–5', { ops: 5 }),
        o('many', '6+', { ops: 12 }, { pain: true, painLabel: 'Tool sprawl (6+ consoles)', cost: ['What do those tools cost a year in licenses and upkeep?', 'dpy'] }),
      ],
    },
    {
      id: 'ops.cost', module: 'ops', phase: 3, type: 'single', weight: 1,
      text: 'Do you need showback / chargeback or cost visibility?', short: 'Cost visibility',
      why: 'Opens NCM Cost Governance (on-prem and cloud).',
      listen: ['Finance asking for per-department cost'],
      probes: ['Who asks for those numbers today?'],
      options: [
        o('onprem', 'Yes, on-prem', { ops: 5 }),
        o('cloud', 'Yes, cloud', { ops: 3, nc2: 3 }),
        o('both', 'Both', { ops: 6, nc2: 3 }),
        o('no', 'No', {}),
      ],
    },
    {
      id: 'res.recovery', module: 'resilience', phase: 3, type: 'single', mustAsk: true, weight: 2, mp: 'M',
      text: 'If ransomware hit on Monday, how long until you’re back?', short: 'Recovery time',
      why: 'Their own answer becomes the metric in the business case.',
      listen: ['Guesswork', 'Dependencies on one person'],
      probes: ['What would that cost per day?'],
      cost: ['What would each day of that cost the business — revenue, overtime, customers?', 'dpd'],
      options: [
        o('hours', 'Hours', {}),
        o('days', 'Days', { cyber: 10 }, { pain: true, painLabel: 'Ransomware recovery would take days' }),
        o('weeks', 'Weeks', { cyber: 15 }, { pain: true, painLabel: 'Ransomware recovery would take weeks' }),
        o('unknown', 'Don’t know', { cyber: 10 }, { pain: true, painLabel: 'Unknown ransomware recovery time' }),
      ],
    },
    {
      id: 'res.network', module: 'resilience', phase: 3, type: 'single', weight: 3,
      text: 'How is the network segmented today?', short: 'Segmentation',
      why: 'A flat network is the clearest microsegmentation (Flow) pain.',
      listen: ['“Everything can talk to everything”', 'Firewall rule sprawl'],
      probes: ['If one VM was compromised, what could it reach?'],
      options: [
        o('flat', 'Mostly flat', { cyber: 15 }, { pain: true, painLabel: 'Flat network — lateral movement risk', cost: ['If one machine was compromised, how many systems could it reach?', 'other'] }),
        o('vlan', 'VLANs by function', { cyber: 8 }),
        o('microseg', 'Microsegmentation (NSX DFW or other)', { cyber: 5, vmw: 3 }),
        o('fw', 'Firewall per app', { cyber: 3 }),
      ],
    },
    {
      id: 'res.immutability', module: 'resilience', phase: 3, type: 'single', weight: 2,
      text: 'Are backups immutable or air-gapped?', short: 'Immutable backups',
      why: 'No immutable copy = no guaranteed ransomware recovery. Opens Objects WORM.',
      listen: ['Backups on the same domain', 'Tape as the only air gap'],
      probes: ['Could an attacker with domain admin delete your backups?'],
      options: [
        o('yes', 'Yes', {}),
        o('partial', 'Partially', { cyber: 5, 'nus.objects': 5 }),
        o('no', 'No / not sure', { cyber: 10, 'nus.objects': 12 }, { pain: true, painLabel: 'Backups not immutable', cost: ['If the backups were hit too, how many days would a rebuild take?', 'days'] }),
      ],
    },
    {
      id: 'cloud.costvis', module: 'cloud', phase: 3, type: 'single', weight: 1,
      text: 'How good is your visibility into cloud spend?', short: 'Cloud cost visibility',
      why: 'Poor visibility opens NCM Cost Governance.',
      listen: ['Surprise bills', 'No tagging'],
      probes: ['Who gets the bill and who explains it?'],
      cost: ['How much cloud spend a month can’t be explained or charged back?', 'dpm'],
      options: [
        o('good', 'Good', {}),
        o('poor', 'Poor', { ops: 5, nc2: 3 }, { pain: true, painLabel: 'Poor cloud cost visibility' }),
        o('none', 'None', { ops: 6, nc2: 3 }, { pain: true, painLabel: 'No cloud cost visibility' }),
      ],
    },
    {
      id: 'stor.pain', module: 'storage', phase: 3, type: 'multi', mustAsk: true, weight: 2,
      text: 'What hurts about storage today?', short: 'Storage pain',
      why: 'Pain decides which NUS capability to lead with.',
      listen: ['Filer renewal quote', 'No S3 on-prem'],
      probes: ['What’s the next storage bill you see coming?'],
      cost: ['What does that cost — dollars a year or hours a month?', 'dpy'],
      options: [
        o('cost', 'Cost per TB', { nus: 5 }, { pain: true, cost: ['What do you spend a year on storage today?', 'dpy'] }),
        o('silos', 'Too many systems / silos', { nus: 8 }, { pain: true, cost: ['How many hours a month go to managing the separate systems?', 'hpm'] }),
        o('ransomware', 'Ransomware exposure', { cyber: 8, 'nus.files': 3 }, { pain: true, cost: ['How much data is exposed, and what would losing it cost?', 'usd'] }),
        o('perf', 'Performance', { nus: 3 }, { pain: true, cost: ['How many people feel it, and how often?', 'people'] }),
        o('naseol', 'NAS refresh / end of life', { nus: 10, 'nus.files': 5 }, { pain: true, cost: ['What’s the renewal or replacement quote?', 'usd'] }),
        o('s3', 'No S3 on-prem', { 'nus.objects': 12 }, { pain: true, cost: ['What do you pay a year for S3 capacity somewhere else?', 'dpy'] }),
      ],
    },
    {
      id: 'edge.mgmt', module: 'edge', phase: 3, type: 'single', mustAsk: true, weight: 2,
      text: 'How do you patch and monitor the sites?', short: 'Site management',
      why: 'Travel and remote hands are measurable costs.',
      listen: ['Windshield time', 'Inconsistent versions'],
      probes: ['How many trips a year?'],
      options: [
        o('central', 'Central tool', {}),
        o('travel', 'Someone travels', { edge: 10 }, { pain: true, painLabel: 'Travel to sites for patching', cost: ['How many hours a month go to travel and site visits?', 'hpm'] }),
        o('hands', 'Remote hands', { edge: 6 }),
        o('poorly', 'Honestly, not well', { edge: 10, cyber: 3 }, { pain: true, painLabel: 'Sites not patched/monitored consistently', cost: ['What did the last site incident cost?', 'usd'] }),
      ],
    },
    {
      id: 'euc.pain', module: 'euc', phase: 3, type: 'multi', mustAsk: true, weight: 2,
      text: 'What hurts about VDI today?', short: 'VDI pain',
      why: 'Picks the lead message for EUC.',
      listen: ['Monday-morning login storms', 'Image update weekends'],
      probes: ['What do users complain about most?'],
      cost: ['What does that cost — hours, dollars, or people affected?', 'hpm'],
      options: [
        o('bundle', 'Licensing tied to the VMware bundle', { euc: 8, 'euc.horizon': 10, vmw: 5 }, { pain: true, cost: ['What does VDI licensing add per year?', 'dpy'] }),
        o('storms', 'Boot / login storms', { euc: 8 }, { pain: true, cost: ['How many users are hit, and how many minutes do they lose each morning?', 'people'] }),
        o('images', 'Image management', { euc: 8 }, { pain: true, cost: ['How many hours a month go to image updates?', 'hpm'] }),
        o('cost', 'Cost per desktop', { euc: 8 }, { pain: true, cost: ['What does VDI cost a year in total?', 'dpy'] }),
        o('ux', 'User experience complaints', { euc: 8 }, { pain: true, cost: ['How many help-desk hours a month go to VDI complaints?', 'hpm'] }),
        o('burst', 'Need to burst desktops to cloud', { euc: 5, nc2: 8 }),
      ],
    },
    {
      id: 'db.provision', module: 'db', phase: 3, type: 'single', mustAsk: true, weight: 3,
      text: 'How long does it take to provision a new database?', short: 'DB provisioning time',
      why: 'The headline NDB metric: days to minutes.',
      listen: ['Ticket queues', 'Developers waiting'],
      probes: ['What’s the process from request to connection string?'],
      cost: ['How many database requests a month, and how many hours does each take?', 'hpm'],
      options: [
        o('minutes', 'Minutes', {}),
        o('hours', 'Hours', { ndb: 5 }),
        o('days', 'Days', { ndb: 15 }, { pain: true, painLabel: 'Days to provision a database' }),
        o('weeks', 'Weeks', { ndb: 18 }, { pain: true, painLabel: 'Weeks to provision a database' }),
      ],
    },
    {
      id: 'db.clones', module: 'db', phase: 3, type: 'single', weight: 2,
      text: 'How do dev/test get production-like copies?', short: 'DB copies',
      why: 'Clone and refresh is where NDB saves the most time and storage.',
      listen: ['Stale test data', 'Full restores for every refresh'],
      probes: ['How often do they refresh, and how long does it take?'],
      cost: ['How many hours does each refresh take, and how often do they run?', 'hpm'],
      options: [
        o('auto', 'Automated clones', {}),
        o('manual', 'Manual restores (days)', { ndb: 12 }, { pain: true, painLabel: 'Manual restores for dev/test copies' }),
        o('none', 'They don’t — test data is stale', { ndb: 8 }, { pain: true, painLabel: 'Stale dev/test data' }),
      ],
    },
    {
      id: 'db.patch', module: 'db', phase: 3, type: 'single', weight: 2,
      text: 'How current is database patching?', short: 'DB patching',
      why: 'Patching backlog is a security and audit risk.',
      listen: ['Unsupported versions'],
      probes: ['What’s the oldest version in production?'],
      cost: ['How many hours would it take to get current?', 'hpm'],
      options: [
        o('current', 'Current', {}),
        o('behind', 'A quarter or more behind', { ndb: 10, cyber: 3 }, { pain: true, painLabel: 'Database patching behind' }),
        o('wayback', 'Way behind / unsupported versions', { ndb: 12, cyber: 5 }, { pain: true, painLabel: 'Unsupported database versions' }),
      ],
    },
    {
      id: 'db.dbaas', module: 'db', phase: 3, type: 'single', weight: 1,
      text: 'Any cloud DBaaS today (RDS, Azure SQL)?', short: 'Cloud DBaaS',
      why: 'Liking cloud DBaaS but not its cost is an NDB-on-prem (or NC2) story.',
      listen: ['Egress and cost surprises'],
      probes: ['What do you like about it?'],
      options: [
        o('like', 'Yes and we like it', {}),
        o('costly', 'Yes but it’s costly', { ndb: 8, nc2: 3 }, { pain: true, painLabel: 'Cloud DBaaS costs', cost: ['What’s the cloud database bill each month?', 'dpm'] }),
        o('no', 'No', {}),
      ],
    },
    {
      id: 'k8s.pain', module: 'k8s', phase: 3, type: 'multi', mustAsk: true, weight: 2,
      text: 'What hurts about Kubernetes today?', short: 'K8s pain',
      why: 'Picks the NKP lead message.',
      listen: ['Cluster drift', 'Upgrade fear'],
      probes: ['How long does a cluster upgrade take?'],
      cost: ['What does that cost — hours a month or dollars a year?', 'hpm'],
      options: [
        o('sprawl', 'Cluster sprawl / day-2 ops', { nkp: 6 }, { pain: true, cost: ['How many hours a month go to cluster upgrades and drift?', 'hpm'] }),
        o('cost', 'License cost', { nkp: 6 }, { pain: true, cost: ['What do platform licenses cost a year?', 'dpy'] }),
        o('skills', 'Skills gap', { nkp: 6 }, { pain: true, cost: ['How many people would you need to hire or contract?', 'people'] }),
        o('security', 'Security / policy consistency', { nkp: 6 }, { pain: true, cost: ['How many hours a month go to keeping policies consistent?', 'hpm'] }),
        o('multicloud', 'Multi-cloud consistency', { nkp: 6 }, { pain: true, cost: ['How many hours a month go to keeping clouds consistent?', 'hpm'] }),
      ],
    },
    {
      id: 'ai.gov', module: 'ai', phase: 3, type: 'multi', mustAsk: true, weight: 2,
      text: 'What worries you about AI adoption?', short: 'AI concerns',
      why: 'Governance and cost worries lead to Agent Gateway.',
      listen: ['Token bills', 'Shadow AI', 'Agents with too much access'],
      probes: ['Who owns AI risk today?'],
      cost: ['What does that cost — or put at risk — today?', 'dpm'],
      options: [
        o('shadow', 'Shadow AI / unsanctioned tools', { 'ai.gov': 12 }, { pain: true, cost: ['How many people use unsanctioned AI tools?', 'people'] }),
        o('tokens', 'Unpredictable token cost', { 'ai.gov': 15 }, { pain: true, cost: ['What’s the monthly token or API bill?', 'dpm'] }),
        o('security', 'Security / access control for agents', { 'ai.gov': 12 }, { pain: true, cost: ['What could an agent with too much access reach?', 'other'] }),
        o('lockin', 'Model lock-in', { 'ai.private': 8 }, { pain: true, cost: ['How much are you committed to spend with one model provider?', 'dpy'] }),
        o('skills', 'Skills to run AI infrastructure', { 'ai.private': 8, ai: 5 }, { pain: true, cost: ['How many people would you need to hire to run it?', 'people'] }),
      ],
    },

    // ═════════════════════════ PHASE 4 · CHANGE & RISK ═════════════════════════
    // Intent to leave or stay → how attached they are → what worries them → preferences.
    {
      id: 'vmw.intent', module: 'vmware', phase: 4, type: 'single', mustAsk: true, weight: 3,
      text: 'What’s the realistic intent with VMware?', short: 'VMware intent',
      why: 'Separates real migrations from price-leverage exercises.',
      listen: ['“We just need a second quote”', 'Executive direction to diversify'],
      probes: ['If price were equal, would you still look at alternatives? Why?'],
      options: [
        o('exit', 'Full exit', { vmw: 20 }),
        o('hedge', 'Reduce footprint / hedge', { vmw: 10 }),
        o('leverage', 'Leverage to negotiate', { vmw: 0 }, { tip: 'Price-only leverage deals rarely close. Dig for pain beyond price: ops toil, hardware age, DR gaps.' }),
        o('undecided', 'Undecided / exploring', { vmw: 5 }),
        o('stay', 'Staying on VMware', { vmw: -30 }),
      ],
    },
    {
      id: 'chg.openness', module: 'change', phase: 4, type: 'single', weight: 2,
      text: 'How does the team feel about making a change?', short: 'Openness to change',
      why: 'Attachment to the current platform is the hidden objection. Know it before you pitch.',
      listen: ['Pride in what they built', '“We know it inside out”', 'Different views across the team'],
      probes: ['Who on the team would be most excited — and most nervous?', 'What would have to be true for the team to feel good about switching?'],
      options: [
        o('eager', 'Eager — they want out', {}),
        o('open', 'Open, if the case is clear', {}),
        o('content', 'Comfortable with how things are', {}, { tip: 'Comfort is the real competitor. Tie the cost of pain to their deadline, or this stalls.' }),
        o('attached', 'Attached — they know it inside out', {}, { tip: 'Respect the investment: lead with what stays the same (their skills, arrays, backup) and a low-risk first step.' }),
        o('split', 'Split — people disagree', {}, { tip: 'Find out who’s for and against. The skeptic may be your technical decision maker.' }),
      ],
    },
    {
      id: 'cloud.refactor', module: 'cloud', phase: 4, type: 'single', weight: 2,
      text: 'Appetite to refactor apps for cloud?', short: 'Refactor appetite',
      why: 'No appetite to refactor is the core NC2 lift-and-shift signal.',
      listen: ['Vendor apps they can’t change', 'Stalled migrations'],
      probes: ['How many apps have you actually refactored so far?'],
      options: [
        o('none', 'None — lift and shift', { nc2: 15 }),
        o('some', 'Some, over time', { nc2: 8, nkp: 5 }),
        o('native', 'Cloud-native only', { nkp: 10, nc2: -5 }),
      ],
    },
    {
      id: 'chg.fears', module: 'change', phase: 4, type: 'multi', mustAsk: true, weight: 3,
      text: 'What worries them most about switching?', short: 'Switching worries',
      why: 'Surfaces the objection early so you can plan to disarm it.',
      listen: ['Past migration scars', 'App vendor certification', 'Systems auditors watch closely'],
      probes: ['What would make you confident enough to move?', 'Which systems would you move last?'],
      options: [
        o('downtime', 'Migration effort and downtime', {}, { tip: 'Nutanix Move: incremental sync plus a scheduled cutover; zero-copy conversion for supported storage.' }),
        o('skills', 'Skills gap — retraining the team', { ops: 3 }, { tip: 'Prism is one console; offer a Test Drive and Nutanix University training.' }),
        o('apps', 'App or vendor compatibility', {}, { tip: 'Check the AHV-validated application list before the next call.' }),
        o('compliance', 'Compliance-sensitive systems (EHR, core banking, PCI)', { cyber: 3 }, { tip: 'Move lower-risk workloads first, and bring compliance in early with a documented plan for the sensitive systems.' }),
        o('tools', 'Backup and tool integrations', {}, { tip: 'Veeam, Commvault, Rubrik, Cohesity and HYCU protect AHV — confirm their versions.' }),
        o('hardware', 'Cost of new hardware', { 'vmw.ext': 10 }, { tip: 'Keep-your-array: NCI Compute on existing Everpure/Dell storage; reuse qualified servers.' }),
        o('risk', 'Picking the wrong vendor', {}, { tip: 'Use peer references in their industry and a scoped POC.' }),
      ],
    },
    {
      id: 'hw.reuse', module: 'hardware', phase: 4, type: 'single', weight: 1,
      text: 'Do you want to reuse any existing hardware?', short: 'Hardware reuse',
      why: 'Reuse points to external storage or qualified servers; a clean slate points to HCI.',
      listen: ['Recently purchased gear', 'Depreciation schedules'],
      probes: ['What’s still on the books?'],
      options: [
        o('servers', 'Yes — recent servers', {}, { tip: 'Check the hardware compatibility list for the servers.' }),
        o('array', 'Yes — the storage array', { 'vmw.ext': 10 }),
        o('clean', 'No — clean slate', { 'vmw.hci': 10, refresh: 5 }),
        o('unsure', 'Not sure', {}),
      ],
    },
    {
      id: 'hw.oem', module: 'hardware', phase: 4, type: 'single', weight: 1,
      text: 'Preferred server vendor or existing contract?', short: 'OEM preference',
      why: 'Nutanix runs on Dell, HPE, Lenovo, Cisco, Fujitsu and NX — align with their procurement path.',
      listen: ['Enterprise agreements', 'Partner loyalty'],
      probes: ['Which partner do you usually buy through?'],
      options: [
        o('dell', 'Dell', {}), o('hpe', 'HPE', {}), o('lenovo', 'Lenovo', {}), o('cisco', 'Cisco', {}),
        o('nx', 'Nutanix NX', {}), o('other', 'Supermicro / other', {}), o('none', 'No preference', {}),
      ],
    },
    {
      id: 'cloud.which', module: 'cloud', phase: 4, type: 'multi', weight: 1,
      text: 'Which cloud(s)?', short: 'Cloud provider',
      why: 'NC2 runs on AWS, Azure, Google Cloud and OVHcloud — bring the right cloud team in.',
      listen: ['Committed spend (EDP / MACC)'],
      probes: ['Do you have committed spend you need to burn down?'],
      options: [o('aws', 'AWS', {}), o('azure', 'Azure', {}), o('gcp', 'Google Cloud', {}), o('ovh', 'OVHcloud', {}), o('undecided', 'Undecided', {})],
    },

    // ═════════════════════════ PHASE 5 · DECISION ═════════════════════════
    // Who signs → process → budget and approval → how they buy → competition → next step.
    {
      id: 'dec.eb', module: 'decision', phase: 5, type: 'single', mustAsk: true, weight: 3, mp: 'E', detail: 'Name / title',
      text: 'Who signs off on this decision?', short: 'Economic buyer',
      why: 'No economic buyer, no deal — find out who can say yes when everyone else says no.',
      listen: ['“It goes up to…”', 'Budget owner vs technical owner'],
      probes: ['Who has signed a purchase like this before?', 'What does that person care about most?'],
      options: [
        o('engaged', 'Identified and engaged', {}, { mp: { E: 2 } }),
        o('known', 'Identified, not met', {}, { mp: { E: 1 } }),
        o('unknown', 'Unknown', {}, { mp: { E: 0 }, tip: 'Ask: “Who else will need to be comfortable with this decision?”' }),
      ],
    },
    {
      id: 'ai.owner', module: 'ai', phase: 5, type: 'single', weight: 1, detail: 'Name / title',
      text: 'Who owns the AI budget?', short: 'AI budget owner',
      why: 'AI budgets often sit outside IT — find the economic buyer.',
      listen: ['CDO / data science', 'Business unit funding'],
      probes: ['Is IT expected to provide the platform?'],
      options: [o('it', 'CIO / IT', {}), o('bu', 'Business unit', {}), o('data', 'Data science / CDO', {}), o('none', 'Not defined', {})],
    },
    {
      id: 'dec.process', module: 'decision', phase: 5, type: 'single', weight: 2, mp: 'DP', detail: 'Steps / dates',
      text: 'What does the evaluation process look like?', short: 'Decision process',
      why: 'Know the steps so you can build a mutual plan.',
      listen: ['POC requirements', 'Committee approvals'],
      probes: ['Walk me through the last time you bought something like this.'],
      options: [
        o('defined', 'Defined steps and dates', {}, { mp: { DP: 2 } }),
        o('informal', 'Informal', {}, { mp: { DP: 1 } }),
        o('unknown', 'Unknown', {}, { mp: { DP: 0 } }),
      ],
    },
    {
      id: 'dec.budget', module: 'decision', phase: 5, type: 'single', mustAsk: true, weight: 3, mp: 'DP', detail: 'Approval threshold / who approves',
      text: 'Is it budgeted — and above what amount does it need higher approval?', short: 'Budget & approval',
      why: 'Budget status and the approval threshold tell you who really signs and how long approval takes.',
      listen: ['A dollar threshold for CFO or board approval', 'Money that must be spent by year-end'],
      probes: ['Above what amount does it go to the CFO or the board?', 'Where would the money come from if it isn’t budgeted?'],
      options: [
        o('approved', 'Budgeted and approved', {}),
        o('planned', 'Planned for the next budget cycle', {}),
        o('find', 'Not budgeted — they’d have to find it', {}, { tip: 'Unbudgeted: the cost of pain is your business case. Find out who can move money.' }),
        o('unknown', 'Not sure', {}, { mp: { DP: 0 }, tip: 'Ask: “Above what amount does a purchase need CFO or board approval?”' }),
      ],
    },
    {
      id: 'dec.timeline', module: 'decision', phase: 5, type: 'single', mustAsk: true, weight: 3, mp: 'DP',
      text: 'When do they want to decide?', short: 'Decision timing',
      why: 'Timing qualifies the forecast.',
      listen: ['End of fiscal year', 'Board meetings'],
      probes: ['What has to be true for you to decide by then?'],
      options: [
        o('30d', 'Within 30 days', {}, { mp: { DP: 2 } }),
        o('qtr', 'This quarter', {}, { mp: { DP: 2 } }),
        o('nextq', 'Next quarter', {}, { mp: { DP: 1 } }),
        o('6m', '6+ months', {}, { mp: { DP: 1 } }),
        o('none', 'No date', {}, { mp: { DP: 0 } }),
      ],
    },
    {
      id: 'dec.paper', module: 'decision', phase: 5, type: 'single', weight: 2, mp: 'PP', detail: 'Partner / vehicle',
      text: 'How do they buy — direct or through a partner?', short: 'Paper process',
      why: 'Procurement and partner path can add weeks — know it early.',
      listen: ['Preferred reseller', 'Legal/security review'],
      probes: ['What does procurement need from us, and how long does it take?'],
      options: [
        o('partner', 'Through a partner / VAR', {}, { mp: { PP: 1 } }),
        o('direct', 'Direct / enterprise agreement', {}, { mp: { PP: 1 } }),
        o('contract', 'Public contract vehicle', {}, { mp: { PP: 1 } }),
        o('rfp', 'Procurement / RFP required', {}, { mp: { PP: 1 } }),
        o('unknown', 'Unknown', {}, { mp: { PP: 0 } }),
      ],
    },
    {
      id: 'cost.model', module: 'cost', phase: 5, type: 'single', weight: 1,
      text: 'How do they prefer to buy?', short: 'Buying model',
      why: 'Subscription terms, marketplace and as-a-service options change the proposal.',
      listen: ['Capex freeze', 'Cloud commits'],
      probes: ['Any committed cloud spend to use?'],
      options: [o('capex', 'Capex', {}), o('opex', 'Opex / subscription', {}), o('aas', 'As-a-service / MSP', { nc2: 3 }), o('any', 'No preference', {})],
    },
    {
      id: 'dec.competition', module: 'decision', phase: 5, type: 'multi', mustAsk: true, weight: 3, mp: 'CO',
      text: 'What else are they looking at?', short: 'Competition',
      why: 'Plant landmines early — the pitch card shows questions for each competitor.',
      listen: ['“Our Microsoft rep said…”', '“We’re also talking to…”'],
      probes: ['What do you like about that option?'],
      options: [
        o('vcf', 'Renew VMware (VCF / VVF)', {}), o('msft', 'Hyper-V / Azure Local', {}), o('proxmox', 'Proxmox', {}),
        o('openshift', 'OpenShift Virtualization', {}), o('hpe', 'HPE VM Essentials', {}), o('scale', 'Scale Computing', {}),
        o('cloud', 'Public cloud native', {}), o('unknown', 'Unknown', {}, { mp: { CO: 0 } }),
      ],
    },
    {
      id: 'dec.criteria', module: 'decision', phase: 5, type: 'multi', weight: 2, mp: 'DC',
      text: 'What will they judge options on?', short: 'Decision criteria',
      why: 'Shape the criteria toward Nutanix strengths early.',
      listen: ['RFP language', 'Must-haves vs nice-to-haves'],
      probes: ['If you could only pick three, which ones?'],
      options: [
        o('tco', 'Cost / TCO', {}), o('simplicity', 'Simplicity / ops', { ops: 3 }), o('migration', 'Migration risk', { vmw: 3 }),
        o('perf', 'Performance', {}), o('security', 'Security / compliance', { cyber: 3 }), o('support', 'Vendor support', {}),
        o('hardware', 'Hardware choice', { 'vmw.ext': 3 }), o('cloud', 'Cloud portability', { nc2: 3 }),
      ],
    },
    {
      id: 'dec.champion', module: 'decision', phase: 5, type: 'single', weight: 3, mp: 'CH', detail: 'Name / title',
      text: 'Who’s pushing for change internally?', short: 'Champion',
      why: 'A champion has power and influence and will sell for you when you’re not in the room.',
      listen: ['Who asked for the meeting', 'Who has a personal win'],
      probes: ['What’s in it for them if this succeeds?'],
      options: [
        o('strong', 'A strong champion (power + influence)', {}, { mp: { CH: 2 } }),
        o('coach', 'A coach (friendly, limited power)', {}, { mp: { CH: 1 } }),
        o('none', 'None yet', {}, { mp: { CH: 0 } }),
      ],
    },
    {
      id: 'dec.success', module: 'decision', phase: 5, type: 'multi', weight: 3, mp: 'M', detail: 'Specific number or target',
      text: 'How will you measure success 12 months from now?', short: 'Success metrics',
      why: 'Metrics you can quantify make the business case and the close plan.',
      listen: ['Numbers', 'Dates', 'Who reports on it'],
      probes: ['What number would make this a win for you personally?'],
      options: [
        o('cost', 'Cost reduction', {}), o('hours', 'Fewer hours on ops', {}), o('rto', 'RTO / RPO met', {}),
        o('migrated', 'Migration done by a date', {}), o('velocity', 'Faster delivery to the business', {}), o('risk', 'Audit / risk items closed', {}),
      ],
    },
    {
      id: 'dec.nextstep', module: 'decision', phase: 5, type: 'multi', mustAsk: true, weight: 3, detail: 'Owner / date',
      text: 'What next step did you agree on?', short: 'Agreed next step',
      why: 'Every call ends with a dated next step, or the deal stalls.',
      listen: ['Who owns it', 'A date on the calendar'],
      probes: ['Can we get that on the calendar now?'],
      options: [
        o('demo', 'Technical deep-dive / demo', {}), o('collector', 'Collector / RVTools sizing', {}), o('testdrive', 'Test Drive', {}),
        o('poc', 'POC', {}), o('tco', 'TCO / business-case workshop', {}), o('exec', 'Exec meeting', {}),
        o('none', 'Nothing agreed', {}, { tip: 'Don’t hang up without a next step — propose one with a date.' }),
      ],
    },
  ];

  F.questionById = Object.fromEntries(F.questions.map((q) => [q.id, q]));
})(globalThis.Fivo = globalThis.Fivo || {});
